CREATE TABLE releases(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),release_number text NOT NULL UNIQUE,commit_sha text NOT NULL,artifact_digest text NOT NULL,lockfile_sha256 text NOT NULL,specification_version text NOT NULL,migration_version text NOT NULL,status text NOT NULL CHECK(status IN('created','building','validated','approved','deploying','deployed','failed','rolling_back','rolled_back','cancelled')),created_by_user_id uuid REFERENCES users(id),approved_by_user_id uuid REFERENCES users(id),approved_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE deployments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),release_id uuid NOT NULL REFERENCES releases(id),environment text NOT NULL CHECK(environment IN('development','test','preview','staging','production')),artifact_digest text NOT NULL,status text NOT NULL CHECK(status IN('pending','started','completed','failed','rollback_started','rolled_back','cancelled')),started_at timestamptz,completed_at timestamptz,initiated_by_user_id uuid REFERENCES users(id),approval_reference text,previous_deployment_id uuid REFERENCES deployments(id),failure_summary text,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE migration_deployments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),deployment_id uuid REFERENCES deployments(id),migration_filename text NOT NULL,checksum text NOT NULL,risk text NOT NULL CHECK(risk IN('low_risk','moderate_risk','high_risk','destructive')),status text NOT NULL CHECK(status IN('planned','started','completed','failed','waived')),estimated_runtime_seconds integer,lock_impact text,backup_verification_run_id uuid REFERENCES backup_verification_runs(id),approved_by_user_id uuid REFERENCES users(id),started_at timestamptz,completed_at timestamptz,failure_summary text,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(deployment_id,migration_filename));
CREATE TABLE security_release_scans(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),release_id uuid NOT NULL REFERENCES releases(id),scan_type text NOT NULL CHECK(scan_type IN('dependency','secret','sast','container','infrastructure','sbom','dast')),status text NOT NULL CHECK(status IN('started','passed','failed','exception_approved')),critical_count integer NOT NULL DEFAULT 0,high_count integer NOT NULL DEFAULT 0,evidence_location text,approved_exception_by_user_id uuid REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz,UNIQUE(release_id,scan_type));
CREATE INDEX deployments_environment_time_idx ON deployments(environment,created_at DESC);CREATE INDEX migration_deployments_status_idx ON migration_deployments(status,risk,created_at);CREATE TRIGGER releases_updated BEFORE UPDATE ON releases FOR EACH ROW EXECUTE FUNCTION set_updated_at();
INSERT INTO permission_definitions(permission_key,description) VALUES
('release.read','Read releases'),('release.create','Create releases'),('release.approve','Approve production releases'),('release.deploy.staging','Deploy staging'),('release.deploy.production','Deploy production'),('release.rollback','Rollback release'),('infrastructure.read','Read infrastructure plans'),('infrastructure.plan','Create infrastructure plans'),('infrastructure.apply','Apply infrastructure'),('migration.read','Read migrations'),('migration.execute','Execute migrations'),('migration.approve_high_risk','Approve high-risk migrations'),('security.scan.read','Read security scans'),('security.exception.manage','Approve security exceptions'),('backup.read','Read backups'),('backup.restore.test','Test restores'),('backup.restore.production','Restore production'),('launch.checklist.read','Read launch checklist'),('launch.checklist.manage','Manage launch checklist'),('launch.approve','Approve launch') ON CONFLICT DO NOTHING;
INSERT INTO role_permission_grants(organization_type,role,permission_key,effect) SELECT 'platform',role,permission,'allow' FROM (VALUES('platform_admin'),('super_admin')) roles(role) CROSS JOIN (VALUES('release.read'),('release.create'),('release.approve'),('release.deploy.staging'),('release.deploy.production'),('release.rollback'),('infrastructure.read'),('infrastructure.plan'),('infrastructure.apply'),('migration.read'),('migration.execute'),('migration.approve_high_risk'),('security.scan.read'),('security.exception.manage'),('backup.read'),('backup.restore.test'),('backup.restore.production'),('launch.checklist.read'),('launch.checklist.manage'),('launch.approve')) permissions(permission) ON CONFLICT DO NOTHING;

CREATE OR REPLACE FUNCTION release_timeline_event() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE audiences jsonb;event_name text;BEGIN SELECT coalesce(jsonb_agg(id::text),'[]'::jsonb) INTO audiences FROM organizations WHERE organization_type='platform' AND status='active';event_name:=TG_ARGV[0]||'.'||NEW.status;INSERT INTO outbox_events(id,event_type,aggregate_type,aggregate_id,payload,metadata,occurred_at) VALUES(gen_random_uuid(),event_name,TG_ARGV[0],NEW.id,jsonb_build_object('status',NEW.status),jsonb_build_object('schemaVersion',1,'timeline',jsonb_build_object('organizationIds',audiences,'category',TG_ARGV[1],'source','release_automation','sourceSystem','deployment_pipeline','summary',initcap(replace(event_name,'.',' ')),'status',NEW.status)),now());RETURN NEW;END $$;
CREATE TRIGGER releases_timeline AFTER INSERT OR UPDATE OF status ON releases FOR EACH ROW EXECUTE FUNCTION release_timeline_event('release','release');
CREATE TRIGGER deployments_timeline AFTER INSERT OR UPDATE OF status ON deployments FOR EACH ROW EXECUTE FUNCTION release_timeline_event('deployment','deployment');
CREATE TRIGGER migration_deployments_timeline AFTER INSERT OR UPDATE OF status ON migration_deployments FOR EACH ROW EXECUTE FUNCTION release_timeline_event('database.migration','migration');
CREATE TRIGGER security_scans_timeline AFTER INSERT OR UPDATE OF status ON security_release_scans FOR EACH ROW EXECUTE FUNCTION release_timeline_event('security.release_scan','security');
