BEGIN;
CREATE TYPE training_requirement_decision AS ENUM('PENDING_MANUFACTURER_REVIEW','NO_NEW_TRAINING_DATA_REQUIRED','TRAINING_DATA_REQUIRED');
CREATE TYPE training_setup_status AS ENUM('NOT_REQUIRED','REQUIREMENTS_DRAFT','EQUIPMENT_NEEDED','EQUIPMENT_ACQUIRED','SETUP_IN_PROGRESS','SAMPLE_REQUIRED','SAMPLE_REVIEW','SETUP_CHANGES_REQUESTED','SETUP_APPROVED','RECORDING','DATA_SUBMITTED','CHANGES_REQUESTED','TRAINING_DATA_APPROVED','REJECTED');
CREATE TYPE training_submission_kind AS ENUM('SAMPLE','FULL','REVISION');
CREATE TYPE training_review_decision AS ENUM('APPROVED','CHANGES_REQUESTED','PARTIALLY_ACCEPTED','REJECTED');

CREATE TABLE guided_training_requirements(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_organization_id uuid NOT NULL REFERENCES organizations(id),manufacturer_id uuid NOT NULL REFERENCES manufacturers(id),contract_id uuid NOT NULL REFERENCES contracts(id),robot_model_id uuid NOT NULL REFERENCES robot_models(id),
 decision training_requirement_decision NOT NULL DEFAULT 'PENDING_MANUFACTURER_REVIEW',retention_policy jsonb NOT NULL DEFAULT '{}',status training_setup_status NOT NULL DEFAULT 'REQUIREMENTS_DRAFT',specification jsonb NOT NULL DEFAULT '{}',required_tier smallint CHECK(required_tier BETWEEN 1 AND 3),requested_by_user_id uuid REFERENCES users(id),decided_at timestamptz,approved_at timestamptz,version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(contract_id,manufacturer_id,robot_model_id));
CREATE TABLE guided_training_kit_items(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),requirement_id uuid NOT NULL REFERENCES guided_training_requirements(id),product_id uuid NOT NULL REFERENCES wearable_catalog_products(id),requirement_status text NOT NULL CHECK(requirement_status IN('REQUIRED','OPTIONAL','ALTERNATIVE')),purpose text NOT NULL,compatibility_notes text,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(requirement_id,product_id));
CREATE TABLE guided_training_equipment_selections(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),requirement_id uuid NOT NULL REFERENCES guided_training_requirements(id),product_id uuid REFERENCES wearable_catalog_products(id),acquisition_status text NOT NULL CHECK(acquisition_status IN('PURCHASED','ALREADY_OWNED','ALTERNATIVE_REQUESTED')),details jsonb NOT NULL DEFAULT '{}',recorded_by_user_id uuid NOT NULL REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE guided_training_readiness(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),requirement_id uuid NOT NULL UNIQUE REFERENCES guided_training_requirements(id),checklist jsonb NOT NULL DEFAULT '{}',calibration_complete boolean NOT NULL DEFAULT false,synchronization_complete boolean NOT NULL DEFAULT false,test_recording_complete boolean NOT NULL DEFAULT false,updated_by_user_id uuid NOT NULL REFERENCES users(id),version integer NOT NULL DEFAULT 1,updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE guided_training_submissions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),requirement_id uuid NOT NULL REFERENCES guided_training_requirements(id),kind training_submission_kind NOT NULL,version integer NOT NULL,status text NOT NULL CHECK(status IN('DRAFT','UPLOADING','VALIDATING','AWAITING_REVIEW','CHANGES_REQUESTED','PARTIALLY_ACCEPTED','APPROVED','REJECTED')),recording_duration_seconds integer NOT NULL DEFAULT 0,metadata jsonb NOT NULL DEFAULT '{}',parent_submission_id uuid REFERENCES guided_training_submissions(id),submitted_by_user_id uuid NOT NULL REFERENCES users(id),submitted_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(requirement_id,version));
CREATE TABLE guided_training_submission_files(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),submission_id uuid NOT NULL REFERENCES guided_training_submissions(id),object_id uuid NOT NULL REFERENCES stored_objects(id),stream_type text NOT NULL,required boolean NOT NULL DEFAULT true,validation_status text NOT NULL DEFAULT 'PENDING' CHECK(validation_status IN('PENDING','VALID','INVALID','MISSING','QUARANTINED')),metadata jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(submission_id,object_id));
CREATE TABLE guided_training_reviews(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),submission_id uuid NOT NULL REFERENCES guided_training_submissions(id),reviewer_user_id uuid NOT NULL REFERENCES users(id),decision training_review_decision NOT NULL,accepted_streams text[] NOT NULL DEFAULT '{}',redo_streams text[] NOT NULL DEFAULT '{}',additional_recordings integer NOT NULL DEFAULT 0,feedback jsonb NOT NULL DEFAULT '{}',comments text,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE guided_training_capture_sessions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),requirement_id uuid NOT NULL REFERENCES guided_training_requirements(id),kind training_submission_kind NOT NULL,status text NOT NULL DEFAULT 'STARTED' CHECK(status IN('STARTED','PAUSED','ENDED','CANCELLED')),instructions_snapshot jsonb NOT NULL DEFAULT '{}',started_by_user_id uuid NOT NULL REFERENCES users(id),started_at timestamptz NOT NULL DEFAULT now(),ended_at timestamptz,updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE guided_training_capture_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),session_id uuid NOT NULL REFERENCES guided_training_capture_sessions(id),event_type text NOT NULL CHECK(event_type IN('STARTED','PAUSED','RESUMED','ENDED','CANCELLED','EQUIPMENT_PROBLEM','PRIVACY_ISSUE')),details jsonb NOT NULL DEFAULT '{}',actor_user_id uuid NOT NULL REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE guided_training_file_access_log(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),file_id uuid NOT NULL REFERENCES guided_training_submission_files(id),organization_id uuid NOT NULL REFERENCES organizations(id),user_id uuid NOT NULL REFERENCES users(id),access_type text NOT NULL DEFAULT 'SIGNED_DOWNLOAD',created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS training_gate_status text NOT NULL DEFAULT 'PENDING_REVIEW' CHECK(training_gate_status IN('PENDING_REVIEW','NOT_REQUIRED','REQUIRED','SETUP_APPROVED','DATA_APPROVED'));
CREATE INDEX guided_training_company_idx ON guided_training_requirements(company_organization_id,status,updated_at DESC);
CREATE INDEX guided_training_manufacturer_idx ON guided_training_requirements(manufacturer_id,status,updated_at DESC);
CREATE TRIGGER guided_training_reviews_immutable BEFORE UPDATE OR DELETE ON guided_training_reviews FOR EACH ROW EXECUTE FUNCTION reject_mutation();
CREATE TRIGGER guided_training_files_immutable BEFORE UPDATE OR DELETE ON guided_training_submission_files FOR EACH ROW EXECUTE FUNCTION reject_mutation();
CREATE TRIGGER guided_training_capture_events_immutable BEFORE UPDATE OR DELETE ON guided_training_capture_events FOR EACH ROW EXECUTE FUNCTION reject_mutation();
CREATE TRIGGER guided_training_file_access_immutable BEFORE UPDATE OR DELETE ON guided_training_file_access_log FOR EACH ROW EXECUTE FUNCTION reject_mutation();
INSERT INTO permission_definitions(permission_key,description) VALUES('training.requirement.read','View authorized guided training requirements'),('training.requirement.company','Manage Company equipment, setup, capture, and submissions'),('training.requirement.manufacturer','Decide, specify, and review Manufacturer training requirements') ON CONFLICT DO NOTHING;
COMMIT;
