import{afterEach,describe,expect,it}from"vitest";import{cleanup,fireEvent,render,screen,within}from"@testing-library/react";import{ActivityTimeline,isTimelineRoute,type TimelineEvent}from"./ActivityTimeline.js";
const events:TimelineEvent[]=[{id:"e1",occurredAt:"2026-08-04T12:00:00.000Z",eventType:"contract.approved",category:"contract",source:"user_action",summary:"Contract approved",details:"Both parties approved version 2.",actorName:"Contract Manager",organizationName:"Example Company",status:"approved",severity:"info",relatedObjects:[{type:"contract",id:"c1",label:"Contract 1",href:"/company/contracts/c1"}]},{id:"e2",occurredAt:"2026-08-04T13:00:00.000Z",eventType:"robot.offline",category:"heartbeat",source:"heartbeat_validation",summary:"Robot offline",organizationName:"Example Manufacturer",status:"offline",severity:"warning",relatedObjects:[{type:"robot",id:"r1",label:"SERIAL-1",href:"/manufacturer/robots/r1"}]}];afterEach(()=>cleanup());
describe("Appendix O unified activity timeline",()=>{
it("recognizes shared timeline routes",()=>{expect(isTimelineRoute("/company/contracts/c1/activity")).toBe(true);expect(isTimelineRoute("/manufacturer/robots/r1/timeline")).toBe(true);expect(isTimelineRoute("/company/contracts")).toBe(false)});
it("renders human-readable events with absolute and relative timestamps",()=>{render(<ActivityTimeline events={events}/>);expect(screen.getByText("Contract approved")).toBeInTheDocument();expect(screen.getAllByRole("time")[0]).toHaveAttribute("datetime")});
it("filters by search",()=>{render(<ActivityTimeline events={events}/>);fireEvent.change(screen.getByLabelText("Search activity"),{target:{value:"offline"}});expect(screen.getByText("Robot offline")).toBeInTheDocument();expect(screen.queryByText("Contract approved")).not.toBeInTheDocument()});
it("filters by category",()=>{render(<ActivityTimeline events={events}/>);fireEvent.change(screen.getByLabelText("Activity category"),{target:{value:"contract"}});expect(screen.getByText("Contract approved")).toBeInTheDocument();expect(screen.queryByText("Robot offline")).not.toBeInTheDocument()});
it("changes chronological ordering",()=>{render(<ActivityTimeline events={events}/>);let items=screen.getAllByRole("listitem");expect(within(items[0]!).getByText("Robot offline")).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Newest first"}));items=screen.getAllByRole("listitem");expect(within(items[0]!).getByText("Contract approved")).toBeInTheDocument()});
it("shows actor and organization while allowing restricted identities",()=>{render(<ActivityTimeline events={events}/>);expect(screen.getByText(/Actor: Contract Manager/)).toBeInTheDocument();expect(screen.getByText(/Actor: System or restricted/)).toBeInTheDocument()});
it("expands details and links related authorized records",()=>{render(<ActivityTimeline events={events}/>);fireEvent.click(screen.getAllByText("Expanded details")[0]!);expect(screen.getByText("Both parties approved version 2.")).toBeInTheDocument();expect(screen.getByRole("link",{name:"contract: Contract 1"})).toHaveAttribute("href","/company/contracts/c1")});
it("has color-independent category and source text",()=>{render(<ActivityTimeline events={events}/>);expect(screen.getByText(/heartbeat - heartbeat validation/)).toBeInTheDocument();expect(screen.getByText(/contract - user action/)).toBeInTheDocument()});
it("provides export and print controls",()=>{render(<ActivityTimeline events={events}/>);expect(screen.getByRole("button",{name:"Export CSV"})).toBeEnabled();expect(screen.getByRole("button",{name:"Print"})).toBeEnabled()});
it("renders an honest authorized empty state",()=>{render(<ActivityTimeline events={[]}/>);expect(screen.getByText("No visible activity")).toBeInTheDocument()});
});

