import {useEffect,useState,type FormEvent,type ReactNode} from "react";
import {Alert,Button,Dialog,EmptyState,ErrorState,FormField,PageHeader,StatusBadge} from "@nation-reserve/design-system";
import {AuthenticatedShell,developmentSessions,OrganizationProvider} from "@nation-reserve/application-shell";
import {api} from "./auth-client.js";

type Row=Record<string,unknown>;type State={loading:boolean;data?:unknown;error?:string};
const org=()=>sessionStorage.getItem("nr-active-organization")??sessionStorage.getItem("currentOrganizationId");
const object=(v:unknown):Row=>v&&typeof v==="object"?v as Row:{};
const list=(v:unknown):Row[]=>Array.isArray(v)?v.filter((x):x is Row=>!!x&&typeof x==="object"):Array.isArray(object(v).items)?object(v).items as Row[]:[];
const label=(v:unknown,fallback="Not available")=>typeof v==="string"&&v?v:fallback;
const scalar=(v:unknown)=>typeof v==="string"||typeof v==="number"||typeof v==="boolean"?String(v):"—";
const amount=(v:unknown)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format((typeof v==="number"?v:typeof v==="string"?Number(v):0)/100);
function useData(path?:string){const[revision,setRevision]=useState(0);const[state,setState]=useState<State>({loading:!!path});useEffect(()=>{if(!path)return;let live=true;void api.get(path).then(data=>{if(live)setState({loading:false,data})}).catch((e:unknown)=>{if(live)setState({loading:false,error:e instanceof Error?e.message:"Unable to load this information."})});return()=>{live=false}},[path,revision]);return{...state,retry:()=>{setState({loading:true});setRevision(v=>v+1)}}}
function Page({title,description,children}:{title:string;description:string;children:ReactNode}){return <section className="owner-page"><PageHeader eyebrow="Robot Owner" title={title} description={description}/>{children}</section>}
function Help({children}:{children:ReactNode}){return <aside className="owner-help"><h2>What this page is about</h2><p>{children}</p></aside>}
function Gap({title,children}:{title:string;children:ReactNode}){return <Alert title={title}>{children}</Alert>}
function Metric({name,value,help}:{name:string;value:ReactNode;help:string}){return <article className="owner-metric"><span>{name}</span><strong>{value}</strong><small>{help}</small></article>}
function Records({state,detail}:{state:State;detail?:((row:Row)=>string)|undefined}){if(state.loading)return <p role="status">Loading…</p>;if(state.error)return <ErrorState description={state.error}/>;const records=list(state.data);if(!records.length&&state.data&&Object.keys(object(state.data)).length)records.push(object(state.data));if(!records.length)return <EmptyState title="No records yet" description="No eligible records were returned for the active organization."/>;return <div className="owner-records">{records.map((row,i)=><article className="nr-card" key={label(row.id,String(i))}><StatusBadge status="general.active"/><h2>{label(row.name??row.statement_number??row.serial_number??row.id,"Record")}</h2><dl>{Object.entries(row).slice(0,8).map(([key,value])=><div key={key}><dt>{key.replaceAll("_"," ")}</dt><dd>{typeof value==="object"?"Available in detail":scalar(value)}</dd></div>)}</dl>{detail&&row.id?<a href={detail(row)}>View details</a>:null}</article>)}</div>}

function Dashboard(){const id=org(),state=useData(id?`/api/v1/organizations/${id}/earnings/summary`:undefined),v=object(state.data);return <Page title="Robot Owner dashboard" description="Robots, verified operation, earnings readiness, and actions that need attention.">{!id&&<Gap title="Choose an organization">Select a Robot Owner organization to load organization-scoped information.</Gap>}<div className="owner-metrics"><Metric name="Robots owned" value="—" help="Owner inventory count is awaiting an API."/><Metric name="Activated" value="—" help="Robots that completed activation."/><Metric name="Assigned" value="—" help="Robots connected to an active assignment."/><Metric name="Operating now" value="—" help="Robots with current valid heartbeat evidence."/><Metric name="Today's earnings" value={state.loading?"…":amount(v.today_minor_units)} help="Gross verified earnings today."/><Metric name="Current month" value={amount(v.month_minor_units??v.net_minor_units)} help="Earnings in the current period."/><Metric name="Financially ready" value={amount(v.financially_ready_minor_units)} help="Processed, but not necessarily payable."/><Metric name="Ready for payout" value={amount(v.ready_for_payout_minor_units)} help="Eligible for payout processing."/></div><div className="owner-grid"><article className="nr-card"><h2>Required actions</h2><ul><li><a href="/owner/payouts/setup">Finish payout setup</a></li><li><a href="/owner/ownership">Resolve ownership issue</a></li><li><a href="/owner/earnings/holds">Review hold</a></li><li><a href="/verify-email/pending">Verify account</a></li></ul></article><article className="nr-card"><h2>Recent notifications</h2><p>The notification feed API is not implemented.</p><a href="/owner/notifications">Review notification destinations</a></article></div><Help>A dash means the platform did not supply a metric; it never means zero. Use required actions to resolve items that can delay activation or payout.</Help></Page>}
function Robots(){return <Page title="Robots" description="The central inventory for robots owned by the active organization."><div className="owner-toolbar"><input aria-label="Search by serial number" placeholder="Search serial number"/><select aria-label="Manufacturer"><option>All manufacturers</option></select><select aria-label="Model"><option>All models</option></select><select aria-label="Status"><option>All statuses</option></select><select aria-label="Availability"><option>Any availability</option></select><select aria-label="Assignment"><option>Any assignment</option></select></div><Gap title="Owner inventory API required">Individual robot detail exists, but the backend does not expose a permission-scoped owner robot list. Filters remain present without fabricating rows.</Gap><a href="/owner/robots/new">Claim a robot</a><Help>Ownership, activation, availability, assignment, operating state, and last heartbeat are separate facts and must never be collapsed into one status.</Help></Page>}
function Robot({id}:{id:string}){const oid=org(),robot=useData(`/api/v1/robots/${id}`),time=useData(oid?`/api/v1/organizations/${oid}/robots/${id}/operating-time`:undefined);return <Page title="Robot details" description="Identity, lifecycle, assignment, and verified operation for one robot."><Records state={robot}/><Gap title="Availability is policy controlled">The current API has no owner availability mutation, so this screen cannot make a local-only change that falsely appears to affect allocation.</Gap><h2>Operating-time history</h2><Records state={time} detail={row=>`/owner/operating-time/${String(row.id)}`}/><Help>A robot may be owned without activation, activated without assignment, and assigned without verified operation. Each lifecycle state is independent.</Help></Page>}
function Claim(){const[msg,setMsg]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget),robotId=d.get("robotId"),transferCode=d.get("transferCode");if(typeof robotId!=="string"||typeof transferCode!=="string")return;try{await api.post(`/api/v1/owner/robots/${robotId}/claim`,{transferCode});setMsg("Ownership claim submitted for verification.")}catch(c){setMsg(c instanceof Error?c.message:"Claim submission failed.")}}return <Page title="Claim robot ownership" description="Connect an eligible registered robot to your organization."><ol className="owner-steps"><li>Enter the platform robot ID and manufacturer transfer code.</li><li>Review identity before submission.</li><li>Nation Reserve verifies the ownership evidence.</li><li>If rejected, review the reason and contact support if needed.</li></ol><form className="account-form" onSubmit={e=>void submit(e)}><FormField label="Robot platform ID" required><input required name="robotId" aria-label="Robot platform ID"/></FormField><FormField label="Transfer code" required><input required name="transferCode" aria-label="Transfer code" autoComplete="off"/></FormField><Button type="submit">Submit ownership claim</Button>{msg&&<p role="status">{msg}</p>}</form><Help>Submission is not approval, activation, assignment, or earnings eligibility. Verification prevents ownership from being attached to the wrong organization.</Help></Page>}
function Ownership({claimId}:{claimId?:string|undefined}){return <Page title={claimId?"Ownership claim":"Ownership verification"} description="Track ownership evidence and review outcomes."><Gap title="Owner claim read API required">The backend supports claim submission and platform review, but no owner-scoped {claimId?"claim detail":"claim listing"} endpoint. {claimId?`Claim ${claimId} was not loaded.`:""}</Gap>{!claimId&&<a href="/owner/robots/new">Start a new claim</a>}<div className="owner-status-list">{["Submitted","Under review","Information required","Approved","Rejected","Cancelled"].map(x=><span key={x}>{x}</span>)}</div><Help>Ownership status records whether Nation Reserve verified the submitted evidence. Rejection does not erase immutable history.</Help></Page>}
function Assignments({id}:{id?:string|undefined}){const oid=org(),state=useData(oid&&id?`/api/v1/organizations/${oid}/assignments/${id}`:undefined);return <Page title={id?"Assignment details":"Assignments"} description="Read-only assignment visibility for owned robots.">{id?<Records state={state}/>:<Gap title="Owner assignment list API required">Assignment detail exists, but the backend does not expose an owner-scoped assignment list.</Gap>}<Help>Owners can review company, manufacturer, facility, department, dates, status, and verified operation. Owners cannot edit assignments.</Help></Page>}
function Operating({id}:{id?:string|undefined}){return <Page title={id?"Verified operating interval":"Operating time"} description="Scheduled time and heartbeat-verified operating time shown separately.">{id?<Gap title="Interval detail API required">No owner interval-detail contract exists for {id}.</Gap>:<><div className="owner-metrics"><Metric name="Today" value="—" help="Verified time today."/><Metric name="Week" value="—" help="Verified time this week."/><Metric name="Month" value="—" help="Verified time this month."/><Metric name="Lifetime" value="—" help="All verified time."/></div><div className="time-comparison" role="img" aria-label="Scheduled time is separate from verified operating time"><span>Scheduled</span><span aria-hidden="true">→</span><strong>Verified</strong></div><Gap title="Owner aggregate API required">Per-robot operating-time evidence exists, but owner-wide totals and interval detail are not exposed.</Gap></>}<Help>This page shows operating time verified through RoboWorkPool’s validation process. Earnings use signed heartbeat evidence, not simply scheduled time.</Help></Page>}
const finance=(kind:string,id?:string)=>{const oid=org();return oid?`/api/v1/organizations/${oid}/earnings/${kind}${id?`/${id}`:""}`:undefined};
function Earnings({kind="summary",id}:{kind?:"summary"|"statements"|"holds"|"disputes";id?:string|undefined}){const state=useData(finance(kind,id)),v=object(state.data),title=id?"Statement details":kind[0]!.toUpperCase()+kind.slice(1);return <Page title={title} description="Backend-calculated financial records; the browser does not recalculate ledger values.">{kind==="summary"&&<div className="owner-metrics"><Metric name="Today" value={amount(v.today_minor_units)} help="Gross verified earnings today."/><Metric name="Week" value={amount(v.week_minor_units)} help="Gross verified earnings this week."/><Metric name="Month" value={amount(v.month_minor_units)} help="Gross verified earnings this month."/><Metric name="Lifetime" value={amount(v.lifetime_minor_units)} help="All gross verified earnings."/><Metric name="Financially ready" value={amount(v.financially_ready_minor_units)} help="Processed, not necessarily payable."/><Metric name="Held" value={amount(v.held_minor_units)} help="Temporarily excluded from progression."/><Metric name="Ready for payout" value={amount(v.ready_for_payout_minor_units)} help="Eligible for payout processing."/></div>}<Records state={state} detail={kind==="statements"?row=>`/owner/earnings/statements/${String(row.id)}`:undefined}/>{kind==="disputes"&&<a href="/support">Contact support about an earnings dispute</a>}<Help>{kind==="statements"?"Statements summarize verified earnings, fees, net amounts, adjustments, holds, and disputes for a period. Statements are not payouts.":kind==="holds"?"A hold temporarily prevents an amount from progressing. Its reason, reviewer, history, and next step should be understandable without technical language.":kind==="disputes"?"Disputes preserve the questioned amount, evidence, review, and outcome without rewriting historical ledger entries.":"Financially Ready, Ready for Payout, Payout Submitted, and Paid are distinct financial states."}</Help></Page>}
function Payouts({mode="overview"}:{mode?:"overview"|"setup"|"history"}){const oid=org(),account=useData(oid?`/api/v1/organizations/${oid}/earnings/payout-account`:undefined),history=useData(oid&&mode==="history"?`/api/v1/organizations/${oid}/payout-attempts`:undefined),[open,setOpen]=useState(false),[msg,setMsg]=useState("");async function begin(){if(!oid)return;try{const result=object(await api.post(`/api/v1/organizations/${oid}/earnings/payout-account/onboarding-link`,{}));if(typeof result.url==="string"&&result.url.startsWith("https://"))location.assign(result.url);else setMsg("No safe onboarding destination was returned.")}catch(c){setMsg(c instanceof Error?c.message:"Unable to begin onboarding.")}setOpen(false)}return <Page title={mode==="setup"?"Payout setup":mode==="history"?"Payout history":"Payouts"} description="Payout readiness and transfers of eligible earnings."><Records state={mode==="history"?history:account}/>{mode==="setup"&&<><ol className="owner-steps"><li>Open the approved processor’s secure onboarding.</li><li>Provide required payout and identity information there.</li><li>Return and refresh payout readiness.</li><li>Eligible earnings proceed only after required checks pass.</li></ol><Button onClick={()=>setOpen(true)}>Begin secure payout setup</Button></>}{msg&&<p role="status">{msg}</p>}<Dialog open={open} title="Continue to secure payout setup?" onClose={()=>setOpen(false)}><p>You may leave RoboWorkPool for the approved payment processor. Do not enter bank credentials directly on this page.</p><Button onClick={()=>void begin()}>Continue securely</Button></Dialog><Help>Payouts transfer eligible earnings after processing completes. Financially Ready does not mean Paid.</Help></Page>}
function Reports(){const oid=org();return <Page title="Reports" description="Generate governed, permission-scoped owner reports."><div className="owner-grid">{[["Earnings report","owner_earnings"],["Operating-time report","owner_operating_time"],["Robot utilization report","owner_robot_utilization"]].map(([name,key])=><article className="nr-card" key={key}><h2>{name}</h2><p>Use shared filters, exports, saved views, and schedules.</p><a href={`/reports?organizationId=${oid??""}&report=${key}`}>Configure report</a></article>)}</div><Help>Reports reuse the reporting infrastructure and governed definitions. They do not calculate earnings or operating time in the browser.</Help></Page>}
function Notifications(){return <Page title="Notifications" description="Owner events with safe deep-link destinations."><Gap title="Notification feed API required">The event catalog defines owner events, but no account notification-feed API is implemented.</Gap><ul className="notification-links">{[["Ownership approved","/owner/ownership"],["Robot activated","/owner/robots"],["Robot assigned","/owner/assignments"],["Robot operating","/owner/operating-time"],["Statement generated","/owner/earnings/statements"],["Payout submitted","/owner/payouts/history"],["Payout completed","/owner/payouts/history"],["Hold placed","/owner/earnings/holds"],["Hold released","/owner/earnings/holds"]].map(([name,href])=><li key={name}><a href={href}>{name}</a></li>)}</ul><Help>Notifications describe a change and link to its record. They never change robot or financial state themselves.</Help></Page>}
function Settings(){return <Page title="Robot Owner settings" description="Organization settings and shared Nation Reserve account controls."><div className="owner-grid"><article className="nr-card"><h2>Organization</h2><a href="/account/organizations">Manage organization context</a></article><article className="nr-card"><h2>Security</h2><a href="/account/security">Manage account security</a></article><article className="nr-card"><h2>Help and support</h2><a href="/support">Contact support</a></article></div><Help>Organization settings affect this Robot Owner organization. Profile, security, sessions, and preferences belong to the shared Nation Reserve account.</Help></Page>}

// eslint-disable-next-line react-refresh/only-export-components
export function isOwnerRoute(path:string){return path==="/owner"||path.startsWith("/owner/")}
export function OwnerPage({path}:{path:string}){if(path==="/owner"||path==="/owner/dashboard")return <Dashboard/>;if(path==="/owner/robots/new")return <Claim/>;const robot=path.match(/^\/owner\/robots\/([^/]+)$/);if(robot)return <Robot id={robot[1]!}/>;if(path==="/owner/robots")return <Robots/>;const claim=path.match(/^\/owner\/ownership\/([^/]+)$/);if(claim)return <Ownership claimId={claim[1]}/>;if(path==="/owner/ownership")return <Ownership/>;const assignment=path.match(/^\/owner\/assignments\/([^/]+)$/);if(assignment)return <Assignments id={assignment[1]}/>;if(path==="/owner/assignments")return <Assignments/>;const interval=path.match(/^\/owner\/operating-time\/([^/]+)$/);if(interval)return <Operating id={interval[1]}/>;if(path==="/owner/operating-time")return <Operating/>;const statement=path.match(/^\/owner\/earnings\/statements\/([^/]+)$/);if(statement)return <Earnings kind="statements" id={statement[1]}/>;if(path==="/owner/earnings/statements")return <Earnings kind="statements"/>;if(path==="/owner/earnings/holds")return <Earnings kind="holds"/>;if(path==="/owner/earnings/disputes")return <Earnings kind="disputes"/>;if(path==="/owner/earnings")return <Earnings/>;if(path==="/owner/payouts/setup")return <Payouts mode="setup"/>;if(path==="/owner/payouts/history")return <Payouts mode="history"/>;if(path==="/owner/payouts")return <Payouts/>;if(path==="/owner/reports")return <Reports/>;if(path==="/owner/notifications")return <Notifications/>;return <Settings/>}
export function OwnerPortalApp(){const[path,setPath]=useState(location.pathname);useEffect(()=>{const update=()=>setPath(location.pathname);addEventListener("popstate",update);return()=>removeEventListener("popstate",update)},[]);return <OrganizationProvider initial={developmentSessions.owner!}><AuthenticatedShell breadcrumbs={[{label:"RoboWorkPool",href:"/"},{label:"Robot Owner",href:"/owner"},{label:"Current page"}]}><OwnerPage path={path}/></AuthenticatedShell></OrganizationProvider>}







