/* eslint-disable @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-base-to-string */
import{useEffect,useState}from"react";import{api}from"./auth-client.js";
type RecordRow=Record<string,unknown>;const labels:Record<string,string>={created:"Created",submitted:"Submitted — awaiting processor confirmation",processing:"Processing — not settled",requires_action:"Action required — not settled",succeeded:"Processor succeeded — settlement pending",settled:"Settled",paid:"Paid",failed:"Failed",unknown:"Unknown — reconciliation required",financially_ready:"Financially ready — payout setup incomplete",payout_ready:"Payout ready",onboarding:"Processor onboarding required",pending_verification:"Processor requirements pending",active:"Processor verification complete"};
export function PaymentPage({path}:{path:string}){const organizationId=sessionStorage.getItem("currentOrganizationId"),[data,setData]=useState<{items?:RecordRow[]}|RecordRow>(),[message,setMessage]=useState(""),endpoint=route(path,organizationId);const load=()=>{if(endpoint)void api.get<{items?:RecordRow[]}|RecordRow>(endpoint).then(setData).catch((e:unknown)=>setMessage(e instanceof Error?e.message:"Unable to load payment data"));};useEffect(load,[endpoint]);const items:RecordRow[]=data&&"items"in data&&Array.isArray(data.items)?data.items:data?[data]:[];
 async function onboarding(){if(!organizationId)return;const response=await api.post<{url:string}>(`/api/v1/organizations/${organizationId}/earnings/payout-account/onboarding-link`);setMessage("Hosted processor onboarding link created.");if(response.url.startsWith("https://"))location.assign(response.url);}
 async function setup(){if(!organizationId)return;await api.post(`/api/v1/organizations/${organizationId}/billing/payment-methods/setup`);setMessage("Secure payment-method setup started. Complete the provider form to activate it.");}
 return <main className="app-shell"><p className="eyebrow">Nation Reserve · Payments</p><section className="page-card"><h1>{title(path)}</h1><p>{guidance(path)}</p>{path.includes("billing/payment-methods")&&<button onClick={()=>void setup()}>Add payment method securely</button>}{path.includes("payout-account")&&<button onClick={()=>void onboarding()}>Continue processor onboarding</button>}{message&&<p role="status" className="notice">{message}</p>}<div className="payment-list" aria-live="polite">{items.length===0?<p>No records yet.</p>:items.map((row,index)=><article key={String(row.id??index)}><strong>{String(row.attempt_number??row.refund_number??row.display_brand??row.provider??"Payment record")}</strong><span className={`badge badge--${tone(String(row.status??"unknown"))}`}>{labels[String(row.status)]??String(row.status??"unknown")}</span>{row.amount_minor_units!==undefined&&<span>{money(row.amount_minor_units)} USD</span>}{row.display_last4!==undefined&&<span>Ending in {String(row.display_last4)}</span>}{row.failure_message_safe!==undefined&&<p role="alert">{String(row.failure_message_safe)}</p>}</article>)}</div><aside className="notice"><strong>Accounting status</strong><p>The RoboWorkPool ledger tracks obligations. Only verified processor evidence confirms external settlement. Submitted never means settled, and payout submitted never means paid.</p></aside></section></main>;}
function route(path:string,organizationId:string|null){if(path.includes("billing/payment-methods"))return organizationId?`/api/v1/organizations/${organizationId}/billing/payment-methods`:undefined;if(path.includes("payout-account"))return organizationId?`/api/v1/organizations/${organizationId}/earnings/payout-account`:undefined;if(path.includes("payment-webhooks"))return"/api/v1/platform/processor-events";if(path.includes("payment-reconciliation"))return"/api/v1/platform/payment-reconciliation-runs";if(path.includes("processor-disputes"))return"/api/v1/platform/processor-disputes";if(path.includes("refunds"))return"/api/v1/platform/refunds";if(path.includes("payout"))return organizationId&&!path.startsWith("/platform")?`/api/v1/organizations/${organizationId}/payout-attempts`:"/api/v1/platform/payout-attempts";return organizationId&&!path.startsWith("/platform")?`/api/v1/organizations/${organizationId}/payment-attempts`:"/api/v1/platform/payment-attempts";}
function title(path:string){if(path.includes("payment-methods"))return"Company payment methods";if(path.includes("payout-account"))return"Owner payout account";if(path.includes("webhook"))return"Processor webhook operations";if(path.includes("reconciliation"))return"Payment reconciliation";if(path.includes("disputes"))return"Processor disputes";if(path.includes("refund"))return"Refund operations";if(path.includes("payout"))return"Payout attempts";return"Payment attempts";}
function guidance(path:string){if(path.includes("payment-methods"))return"Only safe display metadata is stored. Card and bank credentials remain with the payment processor.";if(path.includes("payout-account"))return"Identity and banking details are collected by the hosted processor. Financial readiness alone does not mean payout ready.";return"Review external movement without overriding processor-authoritative status.";}
function money(value:unknown){const cents=typeof value==="number"?value:Number(value??0);return`$${(cents/100).toFixed(2)}`;}function tone(status:string){return["settled","paid","active","succeeded"].includes(status)?"up":["failed","restricted"].includes(status)?"down":"degraded";}