import{useEffect,useState,type FormEvent}from"react";
import{useOrganization}from"@nation-reserve/application-shell";
import{api}from"./auth-client.js";
import{DataView}from"./DataView.js";
type Row=Record<string,unknown>;
type UploadIntent={id:string;upload:{url:string;headers:Record<string,string>}};
type SupportMessage={id:string;author:string;body:string;createdAt:string};
type SupportAttachment={id:string;status:string;scanStatus:string;filename:string};
type SupportTicket={id:string;ticketNumber:string;subject:string;status:string;category:string};
type SupportData={subject?:string;status?:string;messages?:SupportMessage[];attachments?:SupportAttachment[];items?:SupportTicket[]};
type QueueItem={id:string;isMine:boolean;position:number;participant:string;status:string;availableCents:number;reservedCents:number;appliedCents:number};
type QueueData={privacy?:string;currentPosition?:number;items:QueueItem[];authorizedContext?:unknown};
const categories=['ACCOUNT','PAYMENTS','BANK_PAYOUT_ACCOUNT','DOWNPAYMENT_QUEUE','ROBOT_OWNERSHIP','COMPANY_CONTRACT','PURCHASE_ORDER','MANUFACTURER','HEARTBEAT_ROBOT_OFFLINE','TRAINING_DATA','TRAINING_EQUIPMENT','MESSAGING','FILE_UPLOAD','BILLING','REFUND','OTHER'];
const navigate=(path:string)=>{history.pushState({},'',path);dispatchEvent(new PopStateEvent('popstate'))};
const formText=(form:FormData,name:string)=>{const value=form.get(name);return typeof value==='string'?value:''};
function useOrganizationId(){return useOrganization().currentOrganization?.organizationId??''}
function currentUserRole(){return location.pathname.startsWith('/owner')?'ROBOT_OWNER':location.pathname.startsWith('/company')?'COMPANY_OWNER':location.pathname.startsWith('/manufacturer')?'MANUFACTURER':'AUTHENTICATED_USER'}
async function upload(org:string,file:File,setStatus:(value:string)=>void){setStatus(`Uploading ${file.name}â€¦`);const intent=await api.post<UploadIntent>('/api/v1/storage/uploads',{organizationId:org,filename:file.name,contentType:file.type||'application/octet-stream',sizeBytes:file.size},{'Idempotency-Key':crypto.randomUUID()});const response=await fetch(intent.upload.url,{method:'PUT',headers:intent.upload.headers,body:file});if(!response.ok)throw new Error(`Upload failed: ${file.name}`);return intent.id}
export function SupportPage({path}:{path:string}){
 const org=useOrganizationId(),id=path.split('/')[2],[data,setData]=useState<SupportData>(),[status,setStatus]=useState('');
 useEffect(()=>{let active=true;void api.get<SupportData>(id?`/api/v1/support/tickets/${id}`:`/api/v1/organizations/${org}/support/tickets`).then(value=>{if(active)setData(value)}).catch((error:unknown)=>{if(active)setStatus(error instanceof Error?error.message:'Unable to load support')});return()=>{active=false}},[id,org]);
 async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),files=form.getAll('attachments').filter((value):value is File=>value instanceof File&&value.size>0),objectIds:string[]=[];for(const file of files)objectIds.push(await upload(org,file,setStatus));const diagnostics=form.get('diagnostics')==='on'?{appVersion:import.meta.env.MODE,browser:navigator.userAgent,deviceType:navigator.maxTouchPoints?'touch-capable':'desktop',operatingSystem:navigator.platform,currentRoute:location.pathname,userRole:currentUserRole(),organizationId:org,networkStatus:navigator.onLine?'online':'offline',timestamp:new Date().toISOString()}:{};const ticket=await api.post<{id:string}>(`/api/v1/organizations/${org}/support/tickets`,{subject:formText(form,'subject'),category:formText(form,'category'),description:formText(form,'description'),priority:formText(form,'priority'),relatedRecords:safeContext(),diagnosticsSafe:diagnostics,objectIds});navigate(`/support/${ticket.id}`)}
 async function reply(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await api.post(`/api/v1/support/tickets/${id}/replies`,{body:formText(form,'body'),internalNote:false});setStatus('Reply sent.');const updated=await api.get<SupportData>(`/api/v1/support/tickets/${id}`);setData(updated)}
 if(id)return <main className="app-shell"><section className="page-card"><p className="eyebrow">Help & Support</p><h1>{data?.subject??'Support request'}</h1><p>Status: <strong>{data?.status??'Loadingâ€¦'}</strong></p>{data?.messages?.map(message=><article className="card" key={message.id}><strong>{message.author}</strong><p>{message.body}</p><small>{new Date(message.createdAt).toLocaleString()}</small></article>)}<h2>Attachments</h2>{data?.attachments?.map(attachment=><button key={attachment.id} disabled={attachment.status!=='available'||attachment.scanStatus!=='clean'} onClick={()=>{void api.get<{url:string}>(`/api/v1/secure-files/support/${id}/${attachment.id}`).then(result=>window.open(result.url,'_blank','noopener,noreferrer')).catch((error:unknown)=>setStatus(error instanceof Error?error.message:'Unable to open attachment'))}}>{attachment.filename} Â· {attachment.scanStatus}</button>)}<form onSubmit={event=>{void reply(event).catch((error:unknown)=>setStatus(error instanceof Error?error.message:'Unable to send reply'))}}><label>Reply<textarea name="body" required/></label><button>Send reply</button></form>{status&&<p role="status">{status}</p>}</section></main>;
 return <main className="app-shell"><section className="page-card"><p className="eyebrow">Help & Support</p><h1>Contact Support</h1><p>Create a request, safely attach screenshots or documents, and follow the persisted conversation.</p><form onSubmit={event=>{void create(event).catch((error:unknown)=>setStatus(error instanceof Error?error.message:'Unable to create support request'))}}><label>Subject<input name="subject" required minLength={3}/></label><label>Category<select name="category">{categories.map(value=><option key={value}>{value}</option>)}</select></label><label>Priority<select name="priority"><option>NORMAL</option><option>LOW</option><option>HIGH</option><option>URGENT</option></select></label><label>Description<textarea name="description" required minLength={10}/></label><label>Related record ID (optional)<input name="relatedId"/></label><label>File or screenshot<input name="attachments" type="file" multiple accept=".pdf,.png,.jpg,.jpeg,.webp,.txt,.csv,.json,.zip,.docx,.xlsx"/></label><label className="check"><input name="diagnostics" type="checkbox"/>Include diagnostic information (browser, device, route, organization, network, timestamp). Secrets and payment credentials are excluded.</label><button>Create Support Request</button></form>{status&&<p role="status">{status}</p>}<h2>My Support Requests</h2>{data?.items?.length?data.items.map(ticket=><button className="choice" key={ticket.id} onClick={()=>navigate(`/support/${ticket.id}`)}><strong>#{ticket.ticketNumber} {ticket.subject}</strong><span>{ticket.status} Â· {ticket.category}</span></button>):<p>No support requests yet.</p>}<h2>Common help</h2><nav><a href="/support?category=PAYMENTS">Payment help</a> Â· <a href="/support?category=HEARTBEAT_ROBOT_OFFLINE">Robot offline help</a> Â· <a href="/support?category=TRAINING_DATA">Training upload help</a></nav></section></main>
}
function safeContext(){const query=new URLSearchParams(location.search),out:Row={route:location.pathname};for(const key of['contractId','purchaseOrderId','robotSerial','paymentId','conversationId','trainingRequestId']){const value=query.get(key);if(value)out[key]=value}const related=(document.querySelector<HTMLInputElement>('input[name="relatedId"]')?.value??'').trim();if(related)out.relatedRecordId=related;return out}
export function QueuePage(){const org=useOrganizationId(),[data,setData]=useState<QueueData>();useEffect(()=>{let active=true;void api.get<QueueData>(`/api/v1/organizations/${org}/downpayment-queue`).then(value=>{if(active)setData(value)});return()=>{active=false}},[org]);return <main className="app-shell"><section className="page-card"><p className="eyebrow">Funding transparency</p><h1>Down-Payment Queue</h1><p>{data?.privacy??'Participant identities remain private.'}</p>{data?.currentPosition&&<aside className="notice"><strong>Your current queue position: #{data.currentPosition}</strong></aside>}{data&&!data.currentPosition&&<p>You are not currently participating. The queue orders eligible contributions for allocation under platform rules.</p>}<table><thead><tr><th>Position</th><th>Participant</th><th>Status</th><th>Available</th><th>Reserved</th><th>Applied</th></tr></thead><tbody>{data?.items.map(item=><tr key={item.id} className={item.isMine?'selected':''}><td>#{item.position}</td><td>{item.participant}</td><td>{item.status}</td><td>{money(item.availableCents)}</td><td>{money(item.reservedCents)}</td><td>{money(item.appliedCents)}</td></tr>)}</tbody></table>{data?.authorizedContext!==undefined&&<><h2>Authorized contract context</h2><DataView data={data.authorizedContext}/></>}</section></main>}
const adminResources=['users','organizations','contracts','purchase-orders','queue','fleet','heartbeat','finance','webhooks','notifications','storage','training','messaging','audit','health'];
export function AdminCompletionPage({path}:{path:string}){const resource=path.split('/').filter(Boolean).at(-1)??'overview',[data,setData]=useState<unknown>(),[error,setError]=useState('');const endpoint=resource==='support'?'/api/v1/platform/support/tickets':resource==='overview'||resource==='platform'?'/api/v1/platform/completion/overview':`/api/v1/platform/completion/diagnostics/${resource}`;useEffect(()=>{let active=true;void api.get<unknown>(endpoint).then(value=>{if(active)setData(value)}).catch((cause:unknown)=>{if(active)setError(cause instanceof Error?cause.message:'Unable to load diagnostics')});return()=>{active=false}},[endpoint]);return <main className="app-shell"><section className="page-card operations-wide"><p className="eyebrow">Nation Reserve Â· Admin</p><h1>{resource.replaceAll('-',' ')}</h1><p>Safe operational metadata only. Secrets, card data, bank credentials, and heartbeat secrets are never returned.</p><nav>{adminResources.map(value=><a key={value} href={`/platform/admin/${value}`}>{value}</a>)} Â· <a href="/platform/admin/support">support</a> Â· <a href="/platform/health">system health</a> Â· <a href="/platform/feature-flags">feature flags</a></nav>{error?<p role="alert">{error}</p>:<DataView data={data??'Loadingâ€¦'}/>}</section></main>}
const money=(value:unknown)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(value??0)/100);
