import{access}from"node:fs/promises";import{join}from"node:path";import type{SpecificationBundle}from"./loader.js";
export type Severity="critical"|"high"|"medium"|"low";export interface ValidationIssue{issue_code:string;severity:Severity;category:string;message:string;resource_type:string;resource_id:string;source_path?:string;suggested_resolution:string}
const duplicates=(values:string[])=>values.filter((v,i)=>values.indexOf(v)!==i);
export async function validateBundle(bundle:SpecificationBundle):Promise<ValidationIssue[]>{const issues:ValidationIssue[]=[],sources=new Set(bundle.sources.map(s=>s.source_id)),requirements=new Set(bundle.requirements.map(r=>r.requirement_id)),traces=new Map(bundle.traceability.map(t=>[t.requirement_id,t]));
 for(const id of duplicates(bundle.sources.map(s=>s.source_id)))issues.push(issue("SPEC_SOURCE_DUPLICATE","critical","source",id,`Duplicate source ${id}`,"Remove or supersede the duplicate."));
 for(const id of duplicates(bundle.requirements.map(r=>r.requirement_id)))issues.push(issue("SPEC_REQUIREMENT_DUPLICATE","critical","requirement",id,`Duplicate requirement ${id}`,"Preserve one permanent identifier."));
 for(const source of bundle.sources){if(source.file_present&&source.location)try{await access(join(bundle.root,"../..",source.location));}catch{issues.push(issue("SPEC_SOURCE_MISSING","high","source",source.source_id,`Recorded source file is missing: ${source.location}`,"Restore the file or correct file_present.",source.location));}if(!source.file_present)issues.push(issue("SPEC_SOURCE_MISSING",source.source_id==="APP-A"?"critical":"medium","source",source.source_id,source.description,"Manual import or file creation required."));}
 for(const req of bundle.requirements){if(!sources.has(req.source_id))issues.push(issue("SPEC_REQUIREMENT_SOURCE_MISSING","critical","requirement",req.requirement_id,`Unknown source ${req.source_id}`,"Add source registry record."));if(req.scope_status==="current_mvp"&&req.acceptance_criteria.length===0)issues.push(issue("SPEC_REQUIREMENT_ACCEPTANCE_CRITERIA_MISSING","critical","requirement",req.requirement_id,"Current MVP requirement has no acceptance criteria.","Add testable criteria."));const trace=traces.get(req.requirement_id);if(["verified","implemented_unverified"].includes(req.implementation_status)&&(!trace||trace.source_file_paths.length===0))issues.push(issue("SPEC_REQUIREMENT_IMPLEMENTATION_MISSING","critical","requirement",req.requirement_id,"Implemented requirement lacks file evidence.","Map existing implementation evidence."));if(req.implementation_status==="verified"&&(!trace||trace.test_files.length===0))issues.push(issue("SPEC_REQUIREMENT_TEST_MISSING","critical","requirement",req.requirement_id,"Verified requirement lacks test evidence.","Map an executed test."));if(req.immutability==="immutable"&&req.implementation_status==="verified"&&req.validation_status==="test_missing")issues.push(issue("SPEC_IMMUTABLE_RULE_UNTESTED","critical","requirement",req.requirement_id,"Immutable verified requirement is marked test_missing.","Add and execute an invariant test."));}
 for(const trace of bundle.traceability)if(!requirements.has(trace.requirement_id))issues.push(issue("SPEC_BROKEN_REFERENCE","critical","traceability",trace.requirement_id,"Traceability references an unknown requirement.","Correct the identifier."));
 for(const rule of bundle.immutableRules){if(!requirements.has(rule.requirement_id))issues.push(issue("SPEC_IMMUTABLE_RULE_MISSING","critical","immutable_rule",rule.rule_id,"Immutable rule has no valid requirement.","Map it to a permanent requirement."));if(rule.test_status!=="tested")issues.push(issue("SPEC_IMMUTABLE_RULE_UNTESTED","critical","immutable_rule",rule.rule_id,"Current immutable rule lacks executed test evidence.","Add and map an automated test."));if(rule.configuration_override_allowed)issues.push(issue("SPEC_IMMUTABLE_RULE_CONFIGURATION_CONFLICT","critical","immutable_rule",rule.rule_id,"Immutable rule allows configuration override.","Remove the override capability."));}
 for(const screen of bundle.screens){if(!screen.primary_persona||!screen.purpose)issues.push(issue("SPEC_SCREEN_NOT_FULLY_DEFINED","high","screen",screen.screen_id,"Screen lacks persona or purpose.","Complete the screen record."));if(!["public_marketing","authentication"].includes(screen.page_type)&&screen.required_permissions.length===0)issues.push(issue("SPEC_SCREEN_PERMISSION_MISSING","high","screen",screen.screen_id,"Authenticated screen has no permission.","Map backend permission."));if(["planned","partially_specified"].includes(screen.implementation_status))issues.push(issue("SPEC_SCREEN_NOT_FULLY_DEFINED",screen.route==="/"?"critical":"high","screen",screen.screen_id,`${screen.route} is ${screen.implementation_status}.`,"Complete in assigned prompt."));if(screen.test_status==="missing")issues.push(issue("SPEC_SCREEN_TEST_MISSING",screen.route==="/"?"critical":"high","screen",screen.screen_id,`${screen.route} lacks frontend test evidence.`,"Add frontend/accessibility tests."));}
 const links=(bundle.registries["requirement-source-links"] as{items?:Array<{requirement_id:string;source_id:string}>}).items??[];for(const link of links){if(!requirements.has(link.requirement_id)||!sources.has(link.source_id))issues.push(issue("SPEC_BROKEN_REFERENCE","critical","requirement_source_link",`${link.requirement_id}:${link.source_id}`,"Requirement source link references an unknown record.","Correct both permanent identifiers."));}
 const publicPages=(bundle.registries["public-website"] as{items?:Array<{route:string;status:string}>}).items??[];for(const page of publicPages)if(page.status==="planned")issues.push(issue("SPEC_SCREEN_NOT_FULLY_DEFINED",page.route==="/"?"critical":"high","public_page",page.route,`${page.route} is inventoried but not implemented.`,"Implement and test through Prompt 013."));
 const conflicts=(bundle.registries.conflicts as{items?:Array<{conflict_id:string;severity:string;status:string;title:string}>}).items??[];for(const conflict of conflicts)if(conflict.severity==="critical"&&["open","under_review"].includes(conflict.status))issues.push(issue("SPEC_CONFLICT_CRITICAL_OPEN","critical","conflict",conflict.conflict_id,conflict.title,"Resolve through approved repository workflow."));
 return issues.sort((a,b)=>`${a.severity}:${a.issue_code}:${a.resource_id}`.localeCompare(`${b.severity}:${b.issue_code}:${b.resource_id}`));}
function issue(issue_code:string,severity:Severity,category:string,resource_id:string,message:string,suggested_resolution:string,source_path?:string):ValidationIssue{return{issue_code,severity,category,message,resource_type:category,resource_id,suggested_resolution,...(source_path?{source_path}:{})};}
