import { useEffect, useId, useRef, type ButtonHTMLAttributes, type ReactNode } from "react";
export * from "./tokens.js";

export type Tone = "neutral"|"info"|"success"|"warning"|"danger"|"processing"|"held";
export interface StatusDefinition { displayLabel:string; description:string; tone:Tone; icon:string; allowedEntities:string[]; userAction:string|null; terminal:boolean }
export const statuses: Record<string,StatusDefinition> = {
  "general.active":{displayLabel:"Active",description:"This record is currently in effect.",tone:"success",icon:"●",allowedEntities:["general"],userAction:null,terminal:false},
  "general.requires_action":{displayLabel:"Requires action",description:"A user must complete the stated next step.",tone:"warning",icon:"!",allowedEntities:["general"],userAction:"Review the required action.",terminal:false},
  "robot.operating":{displayLabel:"Operating",description:"Valid heartbeat evidence indicates the assigned robot is operating.",tone:"success",icon:"●",allowedEntities:["robot"],userAction:null,terminal:false},
  "robot.offline":{displayLabel:"Offline",description:"The expected heartbeat evidence has stopped.",tone:"danger",icon:"!",allowedEntities:["robot"],userAction:"Review inactivity and recovery guidance.",terminal:false},
  "payment.submitted":{displayLabel:"Submitted",description:"The payment request was sent to the provider; completion is not yet confirmed.",tone:"processing",icon:"↻",allowedEntities:["payment"],userAction:"Wait for a final provider result before retrying.",terminal:false},
  "payment.settled":{displayLabel:"Settled",description:"Company payment is confirmed according to processor evidence.",tone:"success",icon:"✓",allowedEntities:["payment"],userAction:null,terminal:true},
  "payout.financially_ready":{displayLabel:"Financially ready",description:"Earnings passed internal finalization but may not yet satisfy payout conditions.",tone:"info",icon:"i",allowedEntities:["payout"],userAction:"Complete any remaining payout setup.",terminal:false},
  "payout.ready":{displayLabel:"Ready for payout",description:"The amount currently satisfies payout eligibility.",tone:"info",icon:"i",allowedEntities:["payout"],userAction:null,terminal:false},
  "payout.processing":{displayLabel:"Payout processing",description:"The payout was submitted but is not yet confirmed paid.",tone:"processing",icon:"↻",allowedEntities:["payout"],userAction:"Wait for confirmation before taking another action.",terminal:false},
  "payout.paid":{displayLabel:"Paid",description:"The external payout is confirmed complete.",tone:"success",icon:"✓",allowedEntities:["payout"],userAction:null,terminal:true},
  "financial.accrued":{displayLabel:"Accrued",description:"Calculated internally; this amount is not necessarily invoiced or paid.",tone:"info",icon:"i",allowedEntities:["financial"],userAction:null,terminal:false},
  "financial.held":{displayLabel:"Held",description:"Processing is paused pending review or resolution.",tone:"held",icon:"!",allowedEntities:["financial"],userAction:"Review the hold details.",terminal:false},
};
export function Button({variant="primary",loading=false,children,disabled,...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:"primary"|"secondary"|"tertiary"|"danger"|"quiet"|"link";loading?:boolean}){return <button className={`nr-button nr-button--${variant}`} disabled={disabled||loading} aria-busy={loading||undefined} {...props}>{loading?"Working…":children}</button>}
export function FormField({label,description,error,required,children}: {label:string;description?:string;error?:string;required?:boolean;children:ReactNode}){const id=useId();return <div className="nr-field"><div className="nr-field__label">{label}{required&&<span aria-hidden="true"> *</span>}</div>{description&&<div id={`${id}-description`} className="nr-field__description">{description}</div>}<div aria-describedby={[description&&`${id}-description`,error&&`${id}-error`].filter(Boolean).join(" ")||undefined}>{children}</div>{error&&<div id={`${id}-error`} role="alert" className="nr-field__error">{error}</div>}</div>}
export function StatusBadge({status}: {status:string}){const value=statuses[status]??{displayLabel:"Unknown",description:"The current status is not available.",tone:"neutral" as Tone,icon:"?",allowedEntities:[],userAction:null,terminal:false};return <span className={`nr-status nr-status--${value.tone}`} aria-label={`${value.displayLabel}: ${value.description}`}><span aria-hidden="true">{value.icon}</span>{value.displayLabel}</span>}
export function StatusExplanation({status}: {status:string}){const value=statuses[status]??statuses["general.active"]!;return <aside className="nr-explanation"><strong>{value.displayLabel}</strong><p>{value.description}</p>{value.userAction&&<p><strong>Next:</strong> {value.userAction}</p>}</aside>}
export function MoneyAmount({minorUnits,currency="USD",state}: {minorUnits:number;currency?:string;state?:"positive"|"negative"|"held"|"pending"}){return <span className={`nr-money${state?` nr-money--${state}`:""}`}>{new Intl.NumberFormat("en-US",{style:"currency",currency}).format(minorUnits/100)}</span>}
export function RateDisplay({minorUnits,currency="USD",unit="verified hour"}:{minorUnits:number;currency?:string;unit?:string}){return <span><MoneyAmount minorUnits={minorUnits} currency={currency}/> / {unit}</span>}
export function FeeBreakdown({companyBase=500,companyFee=75,ownerGross=500,ownerFee=75,currency="USD"}:{companyBase?:number;companyFee?:number;ownerGross?:number;ownerFee?:number;currency?:string}){return <section className="nr-breakdown" aria-label="Verified operating time rate example"><h3>Rate breakdown</h3><dl><div><dt>Hiring Company base operating charge</dt><dd><MoneyAmount minorUnits={companyBase} currency={currency}/></dd></div><div><dt>Hiring Company platform fee</dt><dd><MoneyAmount minorUnits={companyFee} currency={currency}/></dd></div><div><dt>Hiring Company total</dt><dd><MoneyAmount minorUnits={companyBase+companyFee} currency={currency}/></dd></div><div><dt>Robot Owner gross earning</dt><dd><MoneyAmount minorUnits={ownerGross} currency={currency}/></dd></div><div><dt>Robot Owner platform fee</dt><dd><MoneyAmount minorUnits={ownerFee} currency={currency}/></dd></div><div><dt>Robot Owner net earning</dt><dd><MoneyAmount minorUnits={ownerGross-ownerFee} currency={currency}/></dd></div></dl><p>Charges and earnings are prorated from verified operating time under the active financial configuration.</p></section>}
export const financialTerms={scheduled:"Planned work time. Scheduling alone does not establish payable operation.",verified:"Qualifying operational time supported by heartbeat evidence and applicable assignment rules.",accrued:"Financial value calculated from qualifying verified operation but not necessarily invoiced, settled, or paid.",invoiced:"Amount formally billed to the Hiring Company.",settled:"External company payment confirmed according to processor evidence.",financiallyReady:"Internal calculations and finalization are complete, although payout prerequisites may remain.",readyForPayout:"The amount satisfies applicable payout eligibility requirements.",paid:"External payout has been confirmed completed."} as const;
export function FinancialTermDefinition({term}:{term:keyof typeof financialTerms}){return <span className="nr-term"><strong>{term.replace(/([A-Z])/g," $1")}</strong>: {financialTerms[term]}</span>}
export function DateTime({value,timeZone="UTC"}:{value:string|Date;timeZone?:string}){const date=typeof value==="string"?new Date(value):value;return <time dateTime={date.toISOString()} title={date.toISOString()}>{new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short",timeZone,timeZoneName:"short"}).format(date)}</time>}
export function Duration({seconds}:{seconds:number}){const hours=Math.floor(seconds/3600),minutes=Math.floor(seconds%3600/60);return <span aria-label={`${hours} hours ${minutes} minutes`}>{hours}h {minutes}m</span>}
export function Identifier({label,value}:{label:string;value:string}){return <span className="nr-identifier"><span className="sr-only">{label}: </span><code title={value}>{value}</code><Button variant="quiet" type="button" aria-label={`Copy ${label}`} onClick={()=>void navigator.clipboard?.writeText(value)}>Copy</Button></span>}
export function Alert({tone="info",title,children}: {tone?:Tone;title:string;children:ReactNode}){return <aside className={`nr-alert nr-alert--${tone}`} role={tone==="danger"?"alert":"status"}><strong>{title}</strong><div>{children}</div></aside>}
export function EmptyState({title,description,action}: {title:string;description:string;action?:ReactNode}){return <section className="nr-state"><span aria-hidden="true">○</span><h2>{title}</h2><p>{description}</p>{action}</section>}
export function ErrorState({title="We couldn’t load this page",description,onRetry,reference}: {title?:string;description:string;onRetry?:()=>void;reference?:string}){return <section className="nr-state" role="alert"><span aria-hidden="true">!</span><h2>{title}</h2><p>{description}</p>{reference&&<p>Support reference: <code>{reference}</code></p>}{onRetry&&<Button onClick={onRetry}>Try again</Button>}</section>}
export function PageHeader({eyebrow,title,description,status,actions}: {eyebrow?:string;title:string;description?:string;status?:ReactNode;actions?:ReactNode}){return <header className="nr-page-header" id="page-actions"><div>{eyebrow&&<p className="nr-eyebrow">{eyebrow}</p>}<div className="nr-page-header__title"><h1>{title}</h1>{status}</div>{description&&<p>{description}</p>}</div>{actions&&<div className="nr-page-header__actions">{actions}</div>}</header>}
export function DataTable<T>({caption,columns,rows,getKey}:{caption:string;columns:Array<{key:string;label:string;render:(row:T)=>ReactNode;numeric?:boolean}>;rows:T[];getKey:(row:T)=>string}){return <div className="nr-table-wrap"><table><caption>{caption}</caption><thead><tr>{columns.map(c=><th key={c.key} scope="col" className={c.numeric?"nr-numeric":undefined}>{c.label}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={getKey(row)}>{columns.map(c=><td key={c.key} className={c.numeric?"nr-numeric":undefined} data-label={c.label}>{c.render(row)}</td>)}</tr>)}</tbody></table></div>}
export function Dialog({open,title,children,onClose}: {open:boolean;title:string;children:ReactNode;onClose:()=>void}){const closeRef=useRef<HTMLButtonElement>(null);useEffect(()=>{if(open)closeRef.current?.focus()},[open]);if(!open)return null;return <div className="nr-overlay" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section role="dialog" aria-modal="true" aria-labelledby="nr-dialog-title" className="nr-dialog" onKeyDown={e=>{if(e.key==="Escape")onClose()}}><div className="nr-dialog__header"><h2 id="nr-dialog-title">{title}</h2><button ref={closeRef} className="nr-button nr-button--quiet" onClick={onClose} aria-label="Close dialog">×</button></div>{children}</section></div>}
export function Skeleton({label="Loading content"}:{label?:string}){return <div className="nr-skeleton" role="status"><span className="sr-only">{label}</span></div>}
export function MetricCard({label,value,description,timestamp}:{label:string;value:ReactNode;description:string;timestamp?:string}){return <article className="nr-card"><span>{label}</span><strong className="nr-metric">{value}</strong><p>{description}</p>{timestamp&&<small>Data as of {timestamp}</small>}</article>}
export function ChartContainer({title,description,children,table}:{title:string;description:string;children:ReactNode;table:ReactNode}){return <figure className="nr-card"><figcaption><strong>{title}</strong><p>{description}</p></figcaption>{children}<details><summary>View data table</summary>{table}</details></figure>}
export function Stepper({steps,current}:{steps:Array<{label:string;optional?:boolean}>;current:number}){return <ol className="nr-stepper" aria-label="Progress">{steps.map((step,index)=><li key={step.label} aria-current={index===current?"step":undefined} className={index<current?"is-complete":undefined}><span>{index<current?"✓":index+1}</span>{step.label}{step.optional&&" (optional)"}</li>)}</ol>}
export function ServiceIntroduction({audience="general",variant="standard"}:{audience?:"general"|"robot_owner"|"hiring_company"|"manufacturer";variant?:"compact"|"standard"|"expanded"}){const copy={general:"RoboWorkPool connects verified robot ownership, workforce demand, and manufacturer operational evidence.",robot_owner:"Your earnings are based on verified operating time, not merely availability or scheduling.",hiring_company:"Billing is based only on verified operating time supported by valid heartbeat evidence while assigned.",manufacturer:"Your integration sends signed operational heartbeat evidence. No separate external tracking device is required."};return <aside className={`nr-explanation nr-explanation--${variant}`}><strong>How RoboWorkPool works</strong><p>{copy[audience]}</p></aside>}
export const VerifiedTimeExplanation=({audience}:{audience:"robot_owner"|"hiring_company"|"manufacturer"})=><ServiceIntroduction audience={audience}/>;
export function setTheme(mode:"system"|"light"|"dark"){document.documentElement.dataset.theme=mode;localStorage.setItem("nr-theme",mode)}
