import Fastify from "fastify";
import {describe,expect,it,vi} from "vitest";
import {registerGuidedTrainingRoutes} from "./guided-training-routes.js";
const user="00000000-0000-4000-8000-000000000001",org="00000000-0000-4000-8000-000000000002",id="00000000-0000-4000-8000-000000000003";
function mock(){return{createRequirement:vi.fn(),decide:vi.fn().mockResolvedValue({status:"EQUIPMENT_NEEDED"}),list:vi.fn().mockResolvedValue({items:[]}),detail:vi.fn(),selectEquipment:vi.fn(),readiness:vi.fn(),capture:vi.fn().mockResolvedValue({status:"STARTED"}),createSubmission:vi.fn(),attachFile:vi.fn(),submit:vi.fn(),download:vi.fn().mockResolvedValue({url:"https://private.invalid/signed",expiresInSeconds:300}),review:vi.fn().mockResolvedValue({status:"TRAINING_DATA_APPROVED"})}}
async function setup(){const app=Fastify(),service=mock();await registerGuidedTrainingRoutes(app as never,{service:service as never,authenticate:async()=>({userId:user})});return{app,service}}
describe("guided training API",()=>{
 it("accepts a complete Tier 2 camera-glasses and wrist specification",async()=>{const{app,service}=await setup();const specification={taskName:"Tool sorting",taskDescription:"Sort tools at the workbench",demonstrationInstructions:"Record hands and the complete pick/place motion",numberOfDemonstrations:10,targetRecordingDurationSeconds:300,requiredFirstPersonVideo:true,requiredThirdPersonVideo:false,requiredWristArmMovement:true,requiredHandFingerMotion:false,requiredFullBodyMotion:false,requiredAudio:false,requiredImu:true,otherRequiredStreams:[],cameraResolution:"1080p",frameRate:30,fileTypes:["mp4","csv"],exportFormat:"zip",synchronization:"UTC timestamps",calibrationInstructions:"Run device calibration",workEnvironment:"Production workbench",objectsTools:["wrench"],viewpoints:["first person"],successExamples:[],failureExamples:[],safetyRequirements:"Stop around people",privacyRequirements:"Exclude faces",maximumFileSizeBytes:5000000000};const response=await app.inject({method:"POST",url:`/api/v1/organizations/${org}/manufacturer/training-requirements/${id}/decision`,payload:{decision:"TRAINING_DATA_REQUIRED",requiredTier:2,specification}});expect(response.statusCode).toBe(200);expect(service.decide).toHaveBeenCalledWith(user,org,id,expect.objectContaining({requiredTier:2}));await app.close()});
 it("supports no-new-data without an equipment specification",async()=>{const{app,service}=await setup();const response=await app.inject({method:"POST",url:`/api/v1/organizations/${org}/manufacturer/training-requirements/${id}/decision`,payload:{decision:"NO_NEW_TRAINING_DATA_REQUIRED"}});expect(response.statusCode).toBe(200);expect(service.decide).toHaveBeenCalled();await app.close()});
 it("persists recording transitions and structured review",async()=>{const{app,service}=await setup();expect((await app.inject({method:"POST",url:`/api/v1/organizations/${org}/company/training-requirements/${id}/capture`,payload:{action:"START",kind:"SAMPLE",details:{}}})).statusCode).toBe(200);expect(service.capture).toHaveBeenCalledWith(user,org,id,expect.objectContaining({action:"START"}));const response=await app.inject({method:"POST",url:`/api/v1/organizations/${org}/manufacturer/training-submissions/${id}/review`,payload:{decision:"CHANGES_REQUESTED",acceptedStreams:["first_person_video"],redoStreams:["activity"],additionalRecordings:1,feedback:{reason:"wrist data missing"},comments:"Repeat only wrist stream"}});expect(response.statusCode).toBe(200);expect(service.review).toHaveBeenCalledWith(user,org,id,expect.objectContaining({redoStreams:["activity"]}));await app.close()});
 it("returns only service-authorized short-lived file links",async()=>{const{app,service}=await setup();const response=await app.inject({method:"GET",url:`/api/v1/organizations/${org}/training-files/${id}/download`});expect(response.statusCode).toBe(200);expect(response.json().expiresInSeconds).toBe(300);expect(service.download).toHaveBeenCalledWith(user,org,id);await app.close()});
});
