 
import type{AppFastifyInstance,AppFastifyRequest}from"./fastify-types.js";
import{z}from"zod";import type{PostgresGuidedTrainingService}from"./postgres-guided-training-service.js";
const uuid=z.string().uuid(),org=z.object({organizationId:uuid}),detail=org.extend({id:uuid}),submission=org.extend({submissionId:uuid}),json=z.record(z.string(),z.unknown());
const specification=z.object({taskName:z.string().min(1).max(200),taskDescription:z.string().min(1).max(5000),demonstrationInstructions:z.string().min(1).max(10000),numberOfDemonstrations:z.number().int().positive(),targetRecordingDurationSeconds:z.number().int().positive(),requiredFirstPersonVideo:z.boolean().default(false),requiredThirdPersonVideo:z.boolean().default(false),requiredWristArmMovement:z.boolean().default(false),requiredHandFingerMotion:z.boolean().default(false),requiredFullBodyMotion:z.boolean().default(false),requiredAudio:z.boolean().default(false),requiredImu:z.boolean().default(false),otherRequiredStreams:z.array(z.string().max(80)).default([]),cameraResolution:z.string().max(80).optional(),frameRate:z.number().int().positive().optional(),fileTypes:z.array(z.string().max(50)).default([]),exportFormat:z.string().max(100).optional(),synchronization:z.string().max(1000).optional(),calibrationInstructions:z.string().max(5000).optional(),workEnvironment:z.string().max(5000),objectsTools:z.array(z.string().max(200)).default([]),viewpoints:z.array(z.string().max(200)).default([]),successExamples:z.array(z.string().max(1000)).default([]),failureExamples:z.array(z.string().max(1000)).default([]),safetyRequirements:z.string().max(5000),privacyRequirements:z.string().max(5000),maximumFileSizeBytes:z.number().int().positive(),manufacturerNotes:z.string().max(5000).optional()});
export function registerGuidedTrainingRoutes(app:AppFastifyInstance,options:{service:PostgresGuidedTrainingService;authenticate(r:AppFastifyRequest):Promise<{userId:string}>}){const user=async(r:AppFastifyRequest)=>(await options.authenticate(r)).userId;
 app.post('/api/v1/organizations/:organizationId/manufacturer/training-requirements',async r=>{const p=org.parse(r.params),b=z.object({companyOrganizationId:uuid,contractId:uuid,robotModelId:uuid}).parse(r.body);return options.service.createRequirement(await user(r),p.organizationId,b)});
 app.post('/api/v1/organizations/:organizationId/manufacturer/training-requirements/:id/decision',async r=>{const p=detail.parse(r.params),b=z.discriminatedUnion('decision',[z.object({decision:z.literal('NO_NEW_TRAINING_DATA_REQUIRED')}),z.object({decision:z.literal('TRAINING_DATA_REQUIRED'),requiredTier:z.number().int().min(1).max(3),specification})]).parse(r.body);return options.service.decide(await user(r),p.organizationId,p.id,b)});
 app.get('/api/v1/organizations/:organizationId/company/training-requirements',async r=>{const p=org.parse(r.params);return options.service.list(await user(r),p.organizationId,'company')});
 app.get('/api/v1/organizations/:organizationId/manufacturer/training-requirements',async r=>{const p=org.parse(r.params);return options.service.list(await user(r),p.organizationId,'manufacturer')});
 app.get('/api/v1/organizations/:organizationId/company/training-requirements/:id',async r=>{const p=detail.parse(r.params);return options.service.detail(await user(r),p.organizationId,p.id,'company')});
 app.get('/api/v1/organizations/:organizationId/manufacturer/training-requirements/:id',async r=>{const p=detail.parse(r.params);return options.service.detail(await user(r),p.organizationId,p.id,'manufacturer')});
 app.post('/api/v1/organizations/:organizationId/company/training-requirements/:id/equipment',async r=>{const p=detail.parse(r.params),b=z.object({productId:uuid.optional(),acquisitionStatus:z.enum(['PURCHASED','ALREADY_OWNED','ALTERNATIVE_REQUESTED']),details:json.default({})}).parse(r.body);return options.service.selectEquipment(await user(r),p.organizationId,p.id,b)});
 app.put('/api/v1/organizations/:organizationId/company/training-requirements/:id/readiness',async r=>{const p=detail.parse(r.params),b=z.object({checklist:json,calibrationComplete:z.boolean(),synchronizationComplete:z.boolean(),testRecordingComplete:z.boolean()}).parse(r.body);return options.service.readiness(await user(r),p.organizationId,p.id,b)});
 app.post('/api/v1/organizations/:organizationId/company/training-requirements/:id/capture',async r=>{const p=detail.parse(r.params),b=z.object({action:z.enum(['START','PAUSE','RESUME','END','CANCEL','EQUIPMENT_PROBLEM','PRIVACY_ISSUE']),kind:z.enum(['SAMPLE','FULL','REVISION']).optional(),sessionId:uuid.optional(),details:json.default({})}).parse(r.body);return options.service.capture(await user(r),p.organizationId,p.id,b)});
 app.post('/api/v1/organizations/:organizationId/company/training-requirements/:id/submissions',async r=>{const p=detail.parse(r.params),b=z.object({kind:z.enum(['SAMPLE','FULL','REVISION']),recordingDurationSeconds:z.number().int().nonnegative(),metadata:json.default({}),parentSubmissionId:uuid.optional()}).parse(r.body);return options.service.createSubmission(await user(r),p.organizationId,p.id,b)});
 app.post('/api/v1/organizations/:organizationId/company/training-submissions/:submissionId/files',async r=>{const p=submission.parse(r.params),b=z.object({objectId:uuid,streamType:z.string().min(1).max(80),required:z.boolean().default(true),metadata:json.default({})}).parse(r.body);return options.service.attachFile(await user(r),p.organizationId,p.submissionId,b)});
 app.post('/api/v1/organizations/:organizationId/company/training-submissions/:submissionId/submit',async r=>{const p=submission.parse(r.params);return options.service.submit(await user(r),p.organizationId,p.submissionId)});
 app.get('/api/v1/organizations/:organizationId/training-files/:id/download',async r=>{const p=detail.parse(r.params);return options.service.download(await user(r),p.organizationId,p.id)});
 app.post('/api/v1/organizations/:organizationId/manufacturer/training-submissions/:submissionId/review',async r=>{const p=submission.parse(r.params),b=z.object({decision:z.enum(['APPROVED','CHANGES_REQUESTED','PARTIALLY_ACCEPTED','REJECTED']),acceptedStreams:z.array(z.string().max(80)).default([]),redoStreams:z.array(z.string().max(80)).default([]),additionalRecordings:z.number().int().nonnegative().default(0),feedback:json.default({}),comments:z.string().max(5000).optional()}).parse(r.body);return options.service.review(await user(r),p.organizationId,p.submissionId,b)});
}
