/* eslint-disable @typescript-eslint/no-explicit-any,@typescript-eslint/no-unsafe-argument,@typescript-eslint/require-await,@typescript-eslint/no-base-to-string */
import type{FastifyInstance,FastifyRequest}from"fastify";import{z}from"zod";import type{PostgresOperationsService}from"./postgres-operations-service.js";import type{ApiMetricsRegistry}from"./operations-instrumentation.js";
export async function registerOperationsRoutes(app:FastifyInstance<any,any,any,any>,options:{service:PostgresOperationsService;authenticate(r:FastifyRequest):Promise<{userId:string;sessionId:string}>;rateLimit(userId:string):Promise<boolean>;apiMetrics?:ApiMetricsRegistry}){const announcementQuery=z.object({organizationId:z.string().uuid().optional()});app.get("/api/v1/announcements/active",async r=>options.service.activeAnnouncements(announcementQuery.parse(r.query).organizationId));const principal=async(r:FastifyRequest)=>{const p=await options.authenticate(r);if(!await options.rateLimit(p.userId))throw Object.assign(new Error("ADMIN_RATE_LIMITED"),{statusCode:429,code:"ADMIN_RATE_LIMITED"});return p;},step=(r:FastifyRequest)=>typeof r.headers["x-admin-step-up"]==="string"?r.headers["x-admin-step-up"]:undefined;
 app.post("/api/v1/platform/step-up",async r=>{const p=await principal(r),b=z.object({password:z.string().min(12),purpose:z.enum(["maintenance","job_cancel","acceptance_waiver"])}).parse(r.body);return options.service.issueStepUp(p.userId,p.sessionId,b.password,b.purpose);});
 app.get("/api/v1/platform/dashboard",async r=>options.service.dashboard((await principal(r)).userId));
 app.get("/api/v1/platform/search",async r=>{const p=await principal(r),q=z.object({q:z.string().min(2).max(100)}).parse(r.query);return options.service.search(p.userId,q.q);});
 for(const resource of["feature-flags","configuration","maintenance","announcements","jobs","workers","incidents","audit","diagnostics","alerts"] as const)app.get(`/api/v1/platform/${resource}`,async r=>options.service.list((await principal(r)).userId,resource,(r.query??{})as Record<string,unknown>));
 const flag=z.object({key:z.string().regex(/^[a-z][a-z0-9_]{2,80}$/),name:z.string().min(3),description:z.string().min(3),status:z.enum(["draft","active","disabled","archived"]),enabled:z.boolean(),rolloutPercentage:z.number().int().min(0).max(100),organizationScope:z.array(z.string().uuid()).default([]),userScope:z.array(z.string().uuid()).default([]),reason:z.string().min(3)});
 app.post("/api/v1/platform/feature-flags",async r=>options.service.saveFlag((await principal(r)).userId,flag.parse(r.body)));
 app.patch<{Params:{id:string}}>("/api/v1/platform/feature-flags/:id",async r=>options.service.saveFlag((await principal(r)).userId,flag.omit({key:true}).parse(r.body),r.params.id));
 app.get<{Params:{key:string}}>("/api/v1/platform/feature-flags/:key/evaluate",async r=>{const p=await principal(r),q=z.object({organizationId:z.string().uuid().optional(),userId:z.string().uuid().optional()}).parse(r.query);return options.service.evaluateFlag(r.params.key,{userId:q.userId??p.userId,...(q.organizationId?{organizationId:q.organizationId}:{})});});
 app.patch<{Params:{key:string}}>("/api/v1/platform/configuration/:key",async r=>{const b=z.object({value:z.unknown(),reason:z.string().min(3)}).parse(r.body);return options.service.updateConfiguration((await principal(r)).userId,r.params.key,b);});
 const maintenance=z.object({scopeType:z.enum(["platform","organization","subsystem"]),organizationId:z.string().uuid().optional(),subsystem:z.enum(["payments","billing","robot-registration","assignments","heartbeats","authentication"]).optional(),message:z.string().min(3),startsAt:z.coerce.date(),endsAt:z.coerce.date().optional()});
 app.post("/api/v1/platform/maintenance",async r=>{const p=await principal(r);return options.service.createMaintenance(p.userId,p.sessionId,step(r),maintenance.parse(r.body));});
 const announcement=z.object({title:z.string().min(3),body:z.string().min(3),severity:z.enum(["info","warning","critical"]),scopeType:z.enum(["global","organization","platform"]),organizationId:z.string().uuid().optional(),startsAt:z.coerce.date(),endsAt:z.coerce.date().optional(),dismissible:z.boolean().default(true)});app.post("/api/v1/platform/announcements",async r=>options.service.createAnnouncement((await principal(r)).userId,announcement.parse(r.body)));
 for(const action of["retry","cancel","pause","resume"] as const)app.post<{Params:{id:string}}>(`/api/v1/platform/jobs/:id/${action}`,async r=>{const p=await principal(r);return options.service.jobAction(p.userId,p.sessionId,step(r),r.params.id,action);});
 const incident=z.object({title:z.string().min(3),description:z.string().min(3),severity:z.enum(["low","medium","high","critical"]),assignedToUserId:z.string().uuid().optional(),links:z.array(z.object({entityType:z.string().min(1),entityId:z.string().uuid()})).default([])});app.post("/api/v1/platform/incidents",async r=>options.service.createIncident((await principal(r)).userId,incident.parse(r.body)));app.patch<{Params:{id:string}}>("/api/v1/platform/incidents/:id",async r=>options.service.transitionIncident((await principal(r)).userId,r.params.id,z.object({status:z.enum(["investigating","resolved","closed"]),resolution:z.string().min(3).optional()}).parse(r.body)));
 app.post("/api/v1/platform/alerts/evaluate",async r=>options.service.evaluateAlerts((await principal(r)).userId)); app.get("/api/v1/platform/health",async r=>options.service.health((await principal(r)).userId));app.get("/api/v1/platform/metrics",async(r,reply)=>reply.type("text/plain; version=0.0.4").send((await options.service.metrics((await principal(r)).userId))+(options.apiMetrics?.render()??"")));
 app.get("/api/v1/platform/audit/export",async(r,reply)=>{const result=await options.service.list((await principal(r)).userId,"audit"),rows=result.items as Record<string,unknown>[],columns=["created_at","actor_user_id","action","resource_type","resource_id","source"],cell=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`;return reply.type("text/csv").header("content-disposition","attachment; filename=platform-audit.csv").send([columns.join(","),...rows.map(row=>columns.map(c=>cell(row[c])).join(","))].join("\r\n"));});}
