/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-unsafe-argument */
import{createHmac}from"node:crypto";import{parseApiEnv}from"@nation-reserve/config";import{FakePaymentProvider,StripePaymentProvider,paymentConfigSchema}from"@nation-reserve/payments";import pg from"pg";import{PostgresPaymentService}from"./postgres-payment-service.js";
if(process.env.NODE_ENV==="production"&&process.argv[2]?.startsWith("simulate"))throw new Error("Payment simulators are disabled in production");
const api=parseApiEnv(process.env),config=paymentConfigSchema.parse(process.env),provider=config.PAYMENT_PROVIDER==="stripe"?new StripePaymentProvider(config.PAYMENT_PROVIDER_ENVIRONMENT,config.PAYMENT_PROVIDER_API_KEY!,config.PAYMENT_PROVIDER_WEBHOOK_SECRET,config.PAYMENT_PROVIDER_CONNECT_WEBHOOK_SECRET,config.PAYMENT_REQUEST_TIMEOUT_MS):new FakePaymentProvider((process.env.PAYMENT_FAKE_MODE as any)??"success",config.PAYMENT_PROVIDER_WEBHOOK_SECRET),pool=new pg.Pool({connectionString:api.DATABASE_URL}),service=new PostgresPaymentService(pool,provider,config),command=process.argv[2],userId=process.env.PAYMENT_DEVELOPMENT_USER_ID??"00000000-0000-4000-8000-000000000101";let result:unknown;
if(command==="collect-invoices"||command==="simulate-company-payment")result=await service.collectAutomaticInvoices(userId);
else if(command==="retry")result=await service.retryDue(userId);
else if(command==="reconcile")result=await service.reconcilePayments(userId);
else if(command==="simulate-owner-payout"){const id=process.env.PAYMENT_DEVELOPMENT_STATEMENT_ID;if(!id)throw new Error("PAYMENT_DEVELOPMENT_STATEMENT_ID required");result=await service.payout(userId,id);}
else if(command==="simulate-refund"){const id=process.env.PAYMENT_DEVELOPMENT_PAYMENT_ATTEMPT_ID,adjustment=process.env.PAYMENT_DEVELOPMENT_ADJUSTMENT_ID,amount=Number(process.env.PAYMENT_DEVELOPMENT_REFUND_MINOR_UNITS??0);if(!id||!adjustment||amount<=0)throw new Error("Payment attempt, adjustment, and positive refund amount required");result=await service.refund(userId,id,{amountMinorUnits:amount,financialAdjustmentId:adjustment});}
else if(command==="simulate-webhook"){const objectId=process.env.PAYMENT_DEVELOPMENT_PROVIDER_OBJECT_ID;if(!objectId)throw new Error("PAYMENT_DEVELOPMENT_PROVIDER_OBJECT_ID required");const raw=Buffer.from(JSON.stringify({id:`evt_${Date.now()}`,type:process.env.PAYMENT_DEVELOPMENT_EVENT_TYPE??"payment_intent.succeeded",createdAt:new Date().toISOString(),environment:"test",objectId,status:"succeeded",metadata:{}})),signature=createHmac("sha256",config.PAYMENT_PROVIDER_WEBHOOK_SECRET).update(raw).digest("hex");result=await service.processWebhook(raw,signature);}
else throw new Error("Unknown payment command");process.stdout.write(`${JSON.stringify(result,null,2)}\n`);await pool.end();