import Fastify from"fastify";import{describe,expect,it,vi}from"vitest";import{registerPlatformCompletionRoutes}from"./platform-completion-routes.js";
const user='00000000-0000-4000-8000-000000000001',org='00000000-0000-4000-8000-000000000002',id='00000000-0000-4000-8000-000000000003';
function service(){return{tickets:vi.fn().mockResolvedValue({items:[]}),createTicket:vi.fn().mockResolvedValue({id}),ticket:vi.fn(),reply:vi.fn(),queue:vi.fn().mockResolvedValue({items:[{position:1,participant:'Participant 000001'}]}),adminOverview:vi.fn(),adminTickets:vi.fn(),updateTicket:vi.fn(),diagnostics:vi.fn(),file:vi.fn().mockResolvedValue({url:'https://private.invalid/signed',expiresInSeconds:300})}}
async function setup(){const app=Fastify(),s=service();await registerPlatformCompletionRoutes(app as never,{service:s as never,authenticate:async()=>({userId:user})});return{app,s}}
describe('platform completion API contracts',()=>{
 it('creates categorized support with safe related context and attachment IDs',async()=>{const{app,s}=await setup(),response=await app.inject({method:'POST',url:`/api/v1/organizations/${org}/support/tickets`,payload:{subject:'Training upload failed',category:'TRAINING_DATA',description:'The private upload stopped before completion.',priority:'HIGH',relatedRecords:{trainingRequestId:id},diagnosticsSafe:{browser:'test'},objectIds:[id]}});expect(response.statusCode).toBe(200);expect(s.createTicket).toHaveBeenCalledWith(user,org,expect.objectContaining({category:'TRAINING_DATA',objectIds:[id]}));await app.close()});
 it('rejects unsupported categories before persistence',async()=>{const{app,s}=await setup(),response=await app.inject({method:'POST',url:`/api/v1/organizations/${org}/support/tickets`,payload:{subject:'Invalid category',category:'SECRET_KEYS',description:'This should not be persisted.',priority:'NORMAL'}});expect(response.statusCode).toBe(500);expect(s.createTicket).not.toHaveBeenCalled();await app.close()});
 it('exposes one role-scoped anonymized queue endpoint',async()=>{const{app,s}=await setup(),response=await app.inject({method:'GET',url:`/api/v1/organizations/${org}/downpayment-queue`});expect(response.statusCode).toBe(200);expect(response.json().items[0].participant).toMatch(/Participant/);expect(s.queue).toHaveBeenCalledWith(user,org);await app.close()});
 it('uses an authorization service before returning short-lived files',async()=>{const{app,s}=await setup(),response=await app.inject({method:'GET',url:`/api/v1/secure-files/message/${id}/${id}`});expect(response.statusCode).toBe(200);expect(response.json().expiresInSeconds).toBe(300);expect(s.file).toHaveBeenCalledWith(user,'message',id,id);await app.close()});
});
