/* eslint-disable @typescript-eslint/no-explicit-any */
import type{FastifyInstance,FastifyRequest}from"fastify";import{z}from"zod";import type{PostgresPlatformService}from"./postgres-platform-service.js";
const uuid=z.string().uuid(),page=z.object({limit:z.coerce.number().int().min(1).max(100).default(25),cursor:z.string().datetime().optional()}),idempotency=z.string().min(8).max(200);
export async function registerPlatformRoutes(app:FastifyInstance<any,any,any,any>,options:{service:PostgresPlatformService;authenticate(r:FastifyRequest):Promise<{userId:string}>}){const actor=async(r:FastifyRequest)=>(await options.authenticate(r)).userId;
 app.get("/api/v1/search",async r=>{const q=page.extend({organizationId:uuid,q:z.string().trim().min(1).max(200),types:z.preprocess(v=>typeof v==="string"?v.split(","):v,z.array(z.enum(["robot","manufacturer","company","work_order","contract","conversation","training_package","invoice"])).optional()),sort:z.enum(["relevance","updated"]).default("relevance")}).parse(r.query);return options.service.search(await actor(r),q);});
 app.get("/api/v1/notifications",async r=>options.service.notifications(await actor(r),page.extend({status:z.enum(["pending","delivering","delivered","failed","read","dismissed"]).optional()}).parse(r.query)));
 app.post("/api/v1/notifications/:id/read",async r=>options.service.readNotification(await actor(r),z.object({id:uuid}).parse(r.params).id));
 app.get("/api/v1/conversations",async r=>options.service.conversations(await actor(r),page.parse(r.query)));
 app.get("/api/v1/conversations/:id/messages",async r=>options.service.messages(await actor(r),z.object({id:uuid}).parse(r.params).id,page.parse(r.query)));
 app.post("/api/v1/conversations/:id/messages",async r=>options.service.sendMessage(await actor(r),z.object({id:uuid}).parse(r.params).id,z.object({body:z.string().trim().min(1).max(20000),mentions:z.array(uuid).max(100).default([]),attachments:z.array(z.record(z.string(),z.unknown())).max(20).default([])}).parse(r.body),idempotency.parse(r.headers["idempotency-key"])));
 app.post("/api/v1/storage/uploads",async r=>options.service.createUpload(await actor(r),z.object({organizationId:uuid,filename:z.string().min(1).max(255),contentType:z.string().min(1).max(200),sizeBytes:z.number().int().min(1).max(5_000_000_000),checksumSha256:z.string().regex(/^[a-f0-9]{64}$/).optional()}).parse(r.body),idempotency.parse(r.headers["idempotency-key"])));
 app.post("/api/v1/workflows/:workflowId/transitions",async r=>{const workflowId=z.object({workflowId:uuid}).parse(r.params).workflowId;const body=z.object({organizationId:uuid,action:z.string().regex(/^[a-z][a-z0-9_]*$/),expectedVersion:z.number().int().positive()}).parse(r.body);return options.service.transition(await actor(r),{...body,workflowId},idempotency.parse(r.headers["idempotency-key"]));});
 app.get("/api/v1/openapi.json",async()=>openApi);
}
const openApi={openapi:"3.1.0",info:{title:"RoboWorkPool API",version:"1.0.0",description:"Authenticated, organization-scoped production API. Mutations document related domain and timeline events."},components:{securitySchemes:{bearerAuth:{type:"http",scheme:"bearer",bearerFormat:"JWT"}},schemas:{Error:{type:"object",properties:{error:{type:"object",required:["code","message","requestId"],properties:{code:{type:"string"},message:{type:"string"},requestId:{type:"string"}}}}}}},security:[{bearerAuth:[]}],paths:{"/api/v1/search":{get:{summary:"Search authorized organization records","x-permission":"search.read","responses":{"200":{description:"Paginated search results"},"403":{description:"Forbidden"}}}},"/api/v1/notifications":{get:{summary:"List the authenticated user's notifications",responses:{"200":{description:"Paginated notifications"}}}},"/api/v1/conversations/{id}/messages":{get:{summary:"List messages after participant authorization",responses:{"200":{description:"Messages"},"403":{description:"Not a participant"}}},post:{summary:"Send an idempotent message","x-timeline-events":["message.sent"],responses:{"200":{description:"Message created"},"409":{description:"Idempotency conflict"}}}},"/api/v1/storage/uploads":{post:{summary:"Create a quarantined upload intent","x-permission":"storage.upload","x-background-jobs":["file.malware_scan","file.thumbnail"],responses:{"200":{description:"Upload intent"}}}},"/api/v1/workflows/{workflowId}/transitions":{post:{summary:"Perform an optimistic, idempotent workflow transition","x-permission":"workflow.transition","x-timeline-events":["{workflow}.{action}"],responses:{"200":{description:"Updated workflow"},"409":{description:"Invalid transition or version conflict"}}}}}};
