/* eslint-disable @typescript-eslint/no-explicit-any,@typescript-eslint/no-unsafe-assignment,@typescript-eslint/no-unsafe-member-access,@typescript-eslint/no-unsafe-argument,@typescript-eslint/no-unsafe-return */
import type{Pool}from"pg";import type{PaymentProvider}from"@nation-reserve/payments";
const fail=(code:string,statusCode=400)=>Object.assign(new Error(code),{code,statusCode});
export class PostgresManufacturerFinancialService{constructor(private readonly pool:Pool,private readonly provider:PaymentProvider,private readonly config:{executionEnabled:boolean;country:string;returnUrl:string;refreshUrl:string}){}
 private async scope(userId:string,organizationId:string,write=false){const row=(await this.pool.query(`SELECT mf.id manufacturer_id,m.role FROM manufacturers mf JOIN organization_memberships m ON m.organization_id=mf.organization_id AND m.user_id=$2 AND m.status='active' WHERE mf.organization_id=$1`,[organizationId,userId])).rows[0];if(!row||write&&!['administrator','manager'].includes(row.role))throw fail('PERMISSION_DENIED',403);return row.manufacturer_id as string;}
 private async admin(userId:string){if(!(await this.pool.query(`SELECT 1 FROM platform_role_assignments WHERE user_id=$1 AND status='active' AND role IN('platform_admin','super_admin','operations')`,[userId])).rowCount)throw fail('PERMISSION_DENIED',403);}
 async profile(userId:string,organizationId:string){const id=await this.scope(userId,organizationId);return(await this.pool.query(`INSERT INTO manufacturer_financial_profiles(manufacturer_id) VALUES($1) ON CONFLICT(manufacturer_id) DO UPDATE SET updated_at=manufacturer_financial_profiles.updated_at RETURNING *`,[id])).rows[0];}
 async payables(userId:string,organizationId:string){const id=await this.scope(userId,organizationId);return{items:(await this.pool.query(`SELECT p.*,t.stripe_transfer_id,t.status transfer_status,t.paid_at FROM manufacturer_payables p LEFT JOIN manufacturer_transfers t ON t.payable_id=p.id WHERE p.manufacturer_id=$1 ORDER BY p.created_at DESC`,[id])).rows};}
 async onboarding(userId:string,organizationId:string,key:string){const id=await this.scope(userId,organizationId,true);let p=(await this.pool.query(`SELECT * FROM manufacturer_financial_profiles WHERE manufacturer_id=$1`,[id])).rows[0];if(!p)p=(await this.pool.query(`INSERT INTO manufacturer_financial_profiles(manufacturer_id)VALUES($1)RETURNING *`,[id])).rows[0];if(!p.stripe_connected_account_id){const remote=await this.provider.createOwnerConnectedAccount({organizationId,country:this.config.country,idempotencyKey:key});p=(await this.pool.query(`UPDATE manufacturer_financial_profiles SET stripe_connected_account_id=$2,verification_status='ONBOARDING',updated_at=now() WHERE manufacturer_id=$1 RETURNING *`,[id,remote.id])).rows[0];}return this.provider.createOwnerOnboardingLink({accountId:p.stripe_connected_account_id,returnUrl:this.config.returnUrl,refreshUrl:this.config.refreshUrl});}
 async refresh(userId:string,organizationId:string){const id=await this.scope(userId,organizationId,true),p=(await this.pool.query(`SELECT * FROM manufacturer_financial_profiles WHERE manufacturer_id=$1`,[id])).rows[0];if(!p?.stripe_connected_account_id)throw fail('PAYOUT_ACCOUNT_NOT_STARTED',409);const remote=await this.provider.retrieveConnectedAccount({accountId:p.stripe_connected_account_id});return(await this.pool.query(`UPDATE manufacturer_financial_profiles SET payouts_enabled=$2,charges_enabled=$3,bank_account_linked=$2,verification_status=$4,requirements_due=$5,updated_at=now() WHERE manufacturer_id=$1 RETURNING *`,[id,remote.payoutsEnabled,remote.transfersEnabled,remote.payoutsEnabled&&remote.transfersEnabled?'VERIFIED':remote.detailsSubmitted?'PENDING':'ACTION_REQUIRED',JSON.stringify(remote.requirements)])).rows[0];}
 async createPayable(userId:string,purchaseOrderId:string,input:{grossAmountCents:number;platformFeeCents:number},key:string){await this.admin(userId);if(input.platformFeeCents>input.grossAmountCents)throw fail('INVALID_PLATFORM_FEE',409);const po=(await this.pool.query(`SELECT po.*,ct.manufacturer_id FROM robot_purchase_orders po JOIN contracts ct ON ct.id=po.contract_id WHERE po.id=$1 AND po.status IN('manufacturer_accepted','pending_fulfillment','fulfilled')`,[purchaseOrderId])).rows[0];if(!po)throw fail('PURCHASE_ORDER_NOT_PAYABLE',409);const row=(await this.pool.query(`INSERT INTO manufacturer_payables(manufacturer_id,purchase_order_id,gross_amount_cents,platform_fee_cents,status) VALUES($1,$2,$3,$4,'AVAILABLE') ON CONFLICT(purchase_order_id) DO UPDATE SET updated_at=now() RETURNING *`,[po.manufacturer_id,purchaseOrderId,input.grossAmountCents,input.platformFeeCents])).rows[0];await this.pool.query(`INSERT INTO unified_financial_ledger(organization_id,contract_id,purchase_order_id,transaction_type,amount_cents,direction,status,idempotency_key,metadata) SELECT m.organization_id,po.contract_id,po.id,'MANUFACTURER_PAYABLE',$2,'CREDIT','AVAILABLE',$3,$4 FROM manufacturers m JOIN robot_purchase_orders po ON po.id=$1 WHERE m.id=$5 ON CONFLICT(idempotency_key) DO NOTHING`,[purchaseOrderId,row.net_amount_cents,`payable:${key}`,JSON.stringify({grossAmountCents:input.grossAmountCents,platformFeeCents:input.platformFeeCents}),po.manufacturer_id]);return row;}
 async transfer(userId:string,payableId:string,key:string){await this.admin(userId);if(!this.config.executionEnabled)throw fail('PAYMENT_EXECUTION_DISABLED',409);const row=(await this.pool.query(`SELECT p.*,f.stripe_connected_account_id,f.payouts_enabled,f.bank_account_linked FROM manufacturer_payables p JOIN manufacturer_financial_profiles f ON f.manufacturer_id=p.manufacturer_id WHERE p.id=$1 AND p.status='AVAILABLE'`,[payableId])).rows[0];if(!row||!row.payouts_enabled||!row.bank_account_linked)throw fail('MANUFACTURER_PAYOUT_NOT_READY',409);const created=(await this.pool.query(`INSERT INTO manufacturer_transfers(payable_id,manufacturer_id,stripe_connected_account_id,amount_cents,status,idempotency_key) VALUES($1,$2,$3,$4,'CREATED',$5) ON CONFLICT(idempotency_key) DO UPDATE SET updated_at=now() RETURNING *`,[payableId,row.manufacturer_id,row.stripe_connected_account_id,row.net_amount_cents,key])).rows[0];if(created.stripe_transfer_id)return created;const remote=await this.provider.createOwnerPayout({accountId:row.stripe_connected_account_id,amountMinorUnits:Number(row.net_amount_cents),currency:'USD',idempotencyKey:key}),status=remote.status==='failed'?'FAILED':remote.status==='unknown'?'UNKNOWN':'PROCESSING';await this.pool.query(`UPDATE manufacturer_payables SET status=$2,updated_at=now() WHERE id=$1`,[payableId,status==='FAILED'?'FAILED':'TRANSFER_PROCESSING']);return(await this.pool.query(`UPDATE manufacturer_transfers SET stripe_transfer_id=$2,status=$3,failure_code=$4,updated_at=now() WHERE id=$1 RETURNING *`,[created.id,remote.providerObjectId,status,remote.failureCode??null])).rows[0];}
}
