/* eslint-disable @typescript-eslint/no-explicit-any,@typescript-eslint/no-unsafe-assignment,@typescript-eslint/no-unsafe-member-access,@typescript-eslint/no-unsafe-argument,@typescript-eslint/no-unsafe-return,@typescript-eslint/no-redundant-type-constituents */
import{createHash}from"node:crypto";import{hasPermission,type Permission}from"@nation-reserve/auth";
import{kpis}from"@nation-reserve/analytics";import{forecast,type ForecastResult}from"@nation-reserve/forecasting";
import{csvExport,pdfExport,xlsxExport,type ExportMetadata}from"@nation-reserve/reporting-exports";
import{reportRunSchema,savedReportSchema,scheduledReportSchema}from"@nation-reserve/reporting";import type{Pool}from"pg";
const fail=(code:string,statusCode=400)=>Object.assign(new Error(code),{code,statusCode});
type Scope={organizationId?:string;platform:boolean;organizationType?:string;role:string};
const sources={
 robot_utilization:{view:"robot_daily_summary",date:"summary_date",organization:"owner_organization_id",platform:false},
 company_costs:{view:"company_daily_summary",date:"summary_date",organization:"organization_id",platform:false},
 owner_earnings:{view:"owner_daily_summary",date:"summary_date",organization:"organization_id",platform:false},
 platform_financial_growth:{view:"financial_daily_summary",date:"summary_date",platform:true},
 payment_performance:{view:"payment_daily_summary",date:"summary_date",platform:true},
 heartbeat_reliability:{view:"heartbeat_daily_summary",date:"summary_date",platform:false},
}as const;
export class PostgresReportingService{
 constructor(private readonly pool:Pool){}
 private async scope(userId:string,permission:Permission,organizationId?:string):Promise<Scope>{const platform=(await this.pool.query(`SELECT role FROM platform_role_assignments WHERE user_id=$1 AND status='active'`,[userId])).rows[0];if(platform&&hasPermission("platform",platform.role,permission))return{platform:true,role:platform.role,...(organizationId?{organizationId}:{})};if(!organizationId)throw fail("ORGANIZATION_REQUIRED",400);const member=(await this.pool.query(`SELECT o.organization_type,m.role FROM organization_memberships m JOIN organizations o ON o.id=m.organization_id WHERE m.user_id=$1 AND m.organization_id=$2 AND m.status='active'`,[userId,organizationId])).rows[0];if(!member||!hasPermission(member.organization_type,member.role,permission))throw fail("REPORT_PERMISSION_DENIED",403);return{platform:false,organizationId,organizationType:member.organization_type,role:member.role};}
 async definitions(userId:string,organizationId?:string){const scope=await this.scope(userId,"reports.read",organizationId);return{items:(await this.pool.query(`SELECT id,report_key,name,category,description,version FROM report_definitions WHERE enabled AND ($1 OR NOT platform_only) ORDER BY category,name`,[scope.platform])).rows};}
 async run(userId:string,input:unknown){const parsed=reportRunSchema.parse(input),scope=await this.scope(userId,"reports.read",parsed.organizationId),source=sources[parsed.reportKey as keyof typeof sources];if(!source)throw fail("REPORT_NOT_FOUND",404);if(source.platform&&!scope.platform)throw fail("PLATFORM_REPORT_REQUIRED",403);const definition=(await this.pool.query(`SELECT id,name,version FROM report_definitions WHERE report_key=$1 AND enabled`,[parsed.reportKey])).rows[0];if(!definition)throw fail("REPORT_NOT_FOUND",404);const run=(await this.pool.query(`INSERT INTO report_runs(report_definition_id,requested_by_user_id,organization_id,status,filters,timezone,report_version,started_at)VALUES($1,$2,$3,'running',$4,$5,$6,now()) RETURNING id`,[definition.id,userId,scope.organizationId??null,{...parsed.filters,from:parsed.from,to:parsed.to},parsed.timezone,definition.version])).rows[0];try{const values:any[]=[parsed.from,parsed.to],where=[`${source.date}>=$1::date`,`${source.date}<=$2::date`];if(!source.platform&&"organization"in source&&source.organization&&scope.organizationId){values.push(scope.organizationId);where.push(`${source.organization}=$${values.length}`);}let sql=`SELECT * FROM ${source.view} WHERE ${where.join(" AND ")} ORDER BY ${source.date} LIMIT 10000`;if(parsed.reportKey==="heartbeat_reliability"&&!scope.platform){values.push(scope.organizationId);sql=`SELECT h.* FROM heartbeat_daily_summary h JOIN robots r ON r.id=h.robot_id JOIN manufacturers m ON m.id=r.manufacturer_id WHERE h.summary_date>=$1::date AND h.summary_date<=$2::date AND m.organization_id=$3 ORDER BY h.summary_date LIMIT 10000`;}const rows=(await this.pool.query(sql,values)).rows;await this.pool.query(`UPDATE report_runs SET status='succeeded',finished_at=now(),row_count=$2 WHERE id=$1`,[run.id,rows.length]);return{runId:run.id,report:{key:parsed.reportKey,name:definition.name,version:definition.version},scope:{organizationId:scope.organizationId??null},filters:{...parsed.filters,from:parsed.from,to:parsed.to},timezone:parsed.timezone,generatedAt:new Date().toISOString(),rows};}catch(error){await this.pool.query(`UPDATE report_runs SET status='failed',finished_at=now(),failure_message_safe=$2 WHERE id=$1`,[run.id,error instanceof Error?error.message.slice(0,500):"Report failed"]);throw error;}}
 async dashboard(userId:string,organizationId?:string){const scope=await this.scope(userId,"dashboard.read",organizationId),org=scope.organizationId;if(scope.platform){const [financial,payment,growth]=await Promise.all([this.pool.query(`SELECT COALESCE(SUM(platform_revenue_minor_units),0)::bigint platform_fee_revenue,COALESCE(SUM(verified_seconds),0)::bigint robot_seconds,COALESCE(MAX(active_robots),0)::integer active_robots,COALESCE(MAX(active_companies),0)::integer active_companies FROM financial_daily_summary WHERE summary_date>=CURRENT_DATE-30`),this.pool.query(`SELECT COALESCE(SUM(successful),0)::integer successful,COALESCE(SUM(attempts),0)::integer attempts,COALESCE(SUM(volume_minor_units),0)::bigint volume FROM payment_daily_summary WHERE summary_date>=CURRENT_DATE-30`),this.pool.query(`SELECT summary_date,platform_revenue_minor_units value FROM financial_daily_summary ORDER BY summary_date DESC LIMIT 12`)]);const p=payment.rows[0];return{kind:"executive",widgets:{...financial.rows[0],payment_success_rate:kpis.paymentSuccessRate(p.successful,p.attempts)},trends:growth.rows.reverse()};}if(scope.organizationType==="robot_owner"){const rows=(await this.pool.query(`SELECT * FROM owner_daily_summary WHERE organization_id=$1 ORDER BY summary_date DESC LIMIT 30`,[org])).rows;return{kind:"owner",widgets:rows[0]??{},trends:rows.reverse()};}if(scope.organizationType==="hiring_company"){const rows=(await this.pool.query(`SELECT * FROM company_daily_summary WHERE organization_id=$1 ORDER BY summary_date DESC LIMIT 90`,[org])).rows;return{kind:"company",widgets:rows[0]??{},trends:rows.reverse()};}const rows=(await this.pool.query(`SELECT d.summary_date,COUNT(DISTINCT d.robot_id)::integer robots,COALESCE(SUM(d.verified_seconds),0)::bigint verified_seconds,COALESCE(SUM(d.downtime_seconds),0)::bigint downtime_seconds FROM robot_daily_summary d JOIN manufacturers m ON m.id=d.manufacturer_id WHERE m.organization_id=$1 GROUP BY d.summary_date ORDER BY d.summary_date DESC LIMIT 90`,[org])).rows;return{kind:"manufacturer",widgets:rows[0]??{},trends:rows.reverse()};}
 async kpi(userId:string,organizationId?:string){const dashboard:any=await this.dashboard(userId,organizationId),w=dashboard.widgets;return{robotUtilization:kpis.robotUtilization(w.verified_seconds??w.robot_seconds??0,(w.verified_seconds??w.robot_seconds??0)+(w.downtime_seconds??0)),paymentSuccessRate:w.payment_success_rate??null,generatedAt:new Date().toISOString()};}
 async forecast(userId:string,input:{metric:string;method:ForecastResult["method"];periods:number;organizationId?:string|undefined}){await this.scope(userId,"analytics.forecast",input.organizationId);const allowed:{[key:string]:string}={revenue:"platform_revenue_minor_units",robot_hours:"verified_seconds",payment_volume:"volume_minor_units",robot_growth:"active_robots",organizations:"active_companies",settlement_volume:"company_revenue_minor_units"},column=allowed[input.metric];if(!column)throw fail("FORECAST_METRIC_UNKNOWN",400);const view=input.metric==="payment_volume"?"payment_daily_summary":"financial_daily_summary",rows=(await this.pool.query(`SELECT ${column} value FROM ${view} ORDER BY summary_date DESC LIMIT 24`)).rows.reverse();return{metric:input.metric,...forecast(rows.map(r=>Number(r.value)),input.periods,input.method)};}
 async saved(userId:string,organizationId?:string){await this.scope(userId,"reports.read",organizationId);return{items:(await this.pool.query(`SELECT s.*,d.report_key FROM saved_reports s JOIN report_definitions d ON d.id=s.report_definition_id WHERE s.owner_user_id=$1 OR (s.organization_id=$2 AND s.shared_within_organization) ORDER BY s.favorite DESC,s.updated_at DESC`,[userId,organizationId??null])).rows};}
 async save(userId:string,input:unknown&{organizationId?:string|undefined}){const parsed=savedReportSchema.parse(input);await this.scope(userId,"reports.create",input.organizationId);return(await this.pool.query(`INSERT INTO saved_reports(report_definition_id,owner_user_id,organization_id,name,filters,layout,favorite,shared_within_organization)SELECT id,$2,$3,$4,$5,$6,$7,$8 FROM report_definitions WHERE report_key=$1 RETURNING *`,[parsed.reportKey,userId,input.organizationId??null,parsed.name,parsed.filters,parsed.layout,parsed.favorite,parsed.sharedWithinOrganization])).rows[0]??Promise.reject(fail("REPORT_NOT_FOUND",404));}
 async schedules(userId:string,organizationId?:string){await this.scope(userId,"reports.read",organizationId);return{items:(await this.pool.query(`SELECT s.*,d.report_key FROM scheduled_reports s JOIN report_definitions d ON d.id=s.report_definition_id WHERE s.owner_user_id=$1 OR s.organization_id=$2 ORDER BY s.created_at DESC`,[userId,organizationId??null])).rows};}
 async schedule(userId:string,input:unknown&{organizationId?:string|undefined}){const parsed=scheduledReportSchema.parse(input);await this.scope(userId,"reports.schedule",input.organizationId);return(await this.pool.query(`INSERT INTO scheduled_reports(report_definition_id,owner_user_id,organization_id,name,frequency,recipients,export_type,filters,timezone,enabled,next_run_at)SELECT id,$2,$3,$4,$5,$6,$7,$8,$9,$10,now() FROM report_definitions WHERE report_key=$1 RETURNING *`,[parsed.reportKey,userId,input.organizationId??null,parsed.name,parsed.frequency,parsed.recipients,parsed.exportType,parsed.filters,parsed.timezone,parsed.enabled])).rows[0]??Promise.reject(fail("REPORT_NOT_FOUND",404));}
 async export(userId:string,input:any){await this.scope(userId,"reports.export",input.organizationId);const result=await this.run(userId,input),format=input.exportType as"csv"|"xlsx"|"pdf",metadata:ExportMetadata={generatedAt:result.generatedAt,timezone:result.timezone,organization:result.scope.organizationId??"Nation Reserve Platform",reportVersion:result.report.version,filters:result.filters},body=format==="csv"?csvExport(result.rows,metadata):format==="xlsx"?await xlsxExport(result.rows,metadata):await pdfExport(result.report.name,result.rows,metadata),checksum=createHash("sha256").update(body).digest("hex"),record=(await this.pool.query(`INSERT INTO report_exports(report_run_id,requested_by_user_id,organization_id,export_type,status,content_type,byte_size,checksum_sha256,expires_at,generated_at)VALUES($1,$2,$3,$4,'ready',$5,$6,$7,now()+interval '24 hours',now()) RETURNING id`,[result.runId,userId,result.scope.organizationId,format,format==="csv"?"text/csv":format==="xlsx"?"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":"application/pdf",body.length,checksum,body])).rows[0];return{id:record.id,format,body,checksum};}
}
