/* eslint-disable @typescript-eslint/no-explicit-any,@typescript-eslint/no-unsafe-argument,@typescript-eslint/require-await */
import type{FastifyInstance,FastifyRequest}from"fastify";import{z}from"zod";import type{PostgresReportingService}from"./postgres-reporting-service.js";
const orgQuery=z.object({organizationId:z.string().uuid().optional()}),run=z.object({reportKey:z.string(),organizationId:z.string().uuid().optional(),from:z.coerce.date(),to:z.coerce.date(),timezone:z.string().default("UTC"),filters:z.record(z.string(),z.unknown()).default({})});
export async function registerReportingRoutes(app:FastifyInstance<any,any,any,any>,options:{service:PostgresReportingService;authenticate(r:FastifyRequest):Promise<{userId:string}>}){const actor=async(r:FastifyRequest)=>(await options.authenticate(r)).userId;
 app.get("/api/v1/reports",async r=>{const q=orgQuery.parse(r.query);return options.service.definitions(await actor(r),q.organizationId);});
 app.post("/api/v1/reports/run",async r=>options.service.run(await actor(r),run.parse(r.body)));
 app.get("/api/v1/reports/saved",async r=>{const q=orgQuery.parse(r.query);return options.service.saved(await actor(r),q.organizationId);});
 app.post("/api/v1/reports/saved",async r=>options.service.save(await actor(r),z.object({organizationId:z.string().uuid().optional(),name:z.string(),reportKey:z.string(),filters:z.record(z.string(),z.unknown()).default({}),layout:z.record(z.string(),z.unknown()).default({}),favorite:z.boolean().default(false),sharedWithinOrganization:z.boolean().default(false)}).parse(r.body)));
 app.get("/api/v1/reports/scheduled",async r=>{const q=orgQuery.parse(r.query);return options.service.schedules(await actor(r),q.organizationId);});
 app.post("/api/v1/reports/scheduled",async r=>options.service.schedule(await actor(r),z.object({organizationId:z.string().uuid().optional(),name:z.string(),reportKey:z.string(),frequency:z.enum(["daily","weekly","monthly","quarterly"]),recipients:z.array(z.string().email()),exportType:z.enum(["csv","xlsx","pdf"]),filters:z.record(z.string(),z.unknown()).default({}),timezone:z.string().default("UTC"),enabled:z.boolean().default(true)}).parse(r.body)));
 app.post("/api/v1/reports/export",async(r,reply)=>{const input=run.extend({exportType:z.enum(["csv","xlsx","pdf"])}).parse(r.body),result=await options.service.export(await actor(r),input),contentType=result.format==="csv"?"text/csv":result.format==="xlsx"?"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":"application/pdf";return reply.type(contentType).header("content-disposition",`attachment; filename=roboworkpool-report.${result.format}`).header("x-report-checksum-sha256",result.checksum).send(result.body);});
 app.get("/api/v1/analytics/kpis",async r=>{const q=orgQuery.parse(r.query);return options.service.kpi(await actor(r),q.organizationId);});
 app.get("/api/v1/analytics/trends",async r=>{const q=orgQuery.parse(r.query);return options.service.dashboard(await actor(r),q.organizationId);});
 app.get("/api/v1/analytics/forecast",async r=>{const q=z.object({organizationId:z.string().uuid().optional(),metric:z.enum(["revenue","robot_hours","payment_volume","robot_growth","organizations","settlement_volume"]),method:z.enum(["linear_trend","moving_average","growth_projection"]).default("linear_trend"),periods:z.coerce.number().int().min(1).max(24).default(6)}).parse(r.query);return options.service.forecast(await actor(r),q);});
 app.get("/api/v1/dashboard",async r=>{const q=orgQuery.parse(r.query);return options.service.dashboard(await actor(r),q.organizationId);});
}
