 
import type{AppFastifyInstance,AppFastifyRequest}from"./fastify-types.js";
import{z}from"zod";import type{PostgresResourceService,ResourceType}from"./postgres-resource-service.js";
const uuid=z.string().uuid(),resource=z.enum(["facilities","departments","work-areas","workforce-plans","jobs","responsibilities","training-equipment","training-sessions","training-uploads","training-packages","work-orders","opportunities","support-cases","disputes"]),resourceMap:Record<z.infer<typeof resource>,ResourceType>={facilities:"facility",departments:"department","work-areas":"work_area","workforce-plans":"workforce_plan",jobs:"job",responsibilities:"responsibility","training-equipment":"training_equipment","training-sessions":"training_session","training-uploads":"training_upload","training-packages":"training_package","work-orders":"work_order",opportunities:"opportunity","support-cases":"support_case",disputes:"dispute"},map=(value:z.infer<typeof resource>)=>resourceMap[value],params=z.object({organizationId:uuid,resource}),detail=params.extend({id:uuid}),query=z.object({status:z.string().max(80).optional(),search:z.string().max(200).optional(),limit:z.coerce.number().int().min(1).max(100).default(25),cursor:z.string().datetime().optional(),sort:z.enum(["asc","desc"]).default("desc")}),body=z.object({name:z.string().trim().min(1).max(200),status:z.string().regex(/^[a-z][a-z0-9_]*$/).default("draft"),data:z.record(z.string(),z.unknown()).default({})}),key=z.string().min(8).max(200);
export function registerResourceRoutes(app:AppFastifyInstance,options:{service:PostgresResourceService;authenticate(r:AppFastifyRequest):Promise<{userId:string}>}){const actor=async(r:AppFastifyRequest)=>(await options.authenticate(r)).userId;
 app.get("/api/v1/organizations/:organizationId/:resource",async r=>{const p=params.parse(r.params);return options.service.list(await actor(r),p.organizationId,map(p.resource),query.parse(r.query));});
 app.get("/api/v1/organizations/:organizationId/:resource/:id",async r=>{const p=detail.parse(r.params);return options.service.get(await actor(r),p.organizationId,map(p.resource),p.id);});
 app.post("/api/v1/organizations/:organizationId/:resource",async r=>{const p=params.parse(r.params);return options.service.create(await actor(r),p.organizationId,map(p.resource),body.parse(r.body),key.parse(r.headers["idempotency-key"]));});
 app.patch("/api/v1/organizations/:organizationId/:resource/:id",async r=>{const p=detail.parse(r.params),input=body.partial().extend({expectedVersion:z.number().int().positive()}).parse(r.body);return options.service.update(await actor(r),p.organizationId,map(p.resource),p.id,input,key.parse(r.headers["idempotency-key"]));});
}


